Repository deephaven/web-client-ui, pull requests merged in 2021-06, with the labels that each got.

#53 Add proper translations for all chart source types
  packages/chart/src/ChartUtils.js
Labels: bug

#50 Context Menu Typescript
  packages/components/src/context-actions/ContextActionUtils.ts
  packages/components/src/context-actions/ContextActions.test.jsx
  packages/components/src/context-actions/ContextActions.tsx
  packages/components/src/context-actions/ContextMenu.tsx
  packages/components/src/context-actions/ContextMenuItem.jsx
  packages/components/src/context-actions/ContextMenuItem.tsx
  packages/components/src/context-actions/ContextMenuRoot.tsx
  packages/components/src/context-actions/GlobalContextAction.tsx
  packages/components/src/context-actions/GlobalContextActions.tsx
  packages/components/src/context-actions/__snapshots__/ContextActions.test.jsx.snap
  packages/utils/src/Pending.ts
  packages/utils/src/PromiseUtils.test.js
  packages/utils/src/PromiseUtils.ts
  packages/utils/src/index.js
Labels: typescript

#56 TS Components Chunk 4
  packages/components/package.json
  packages/components/src/DebouncedSearchInput.tsx
  packages/components/src/DeephavenSpinner.jsx
  packages/components/src/DeephavenSpinner.tsx
  packages/components/src/DraggableItemList.tsx
  packages/components/src/ItemList.tsx
  packages/components/src/ItemListItem.tsx
  packages/components/src/LoadingOverlay.tsx
  packages/components/src/LoadingSpinner.tsx
  packages/components/src/SearchInput.tsx
  packages/components/src/context-actions/ContextActionUtils.ts
  packages/components/src/popper/Popper.tsx
  packages/components/src/popper/Tooltip.tsx
  packages/eslint-config/index.js
  packages/utils/src/RangeUtils.ts
  packages/utils/src/index.ts
Labels: typescript

#54 enterprise update
  package-lock.json
  packages/chart/package-lock.json
  packages/chart/src/Chart.jsx
  packages/code-studio/package-lock.json
  packages/code-studio/src/controls/markdown/MarkdownEditor.jsx
  packages/components/package-lock.json
  packages/components/src/index.d.ts
  packages/console/package-lock.json
  packages/grid/package-lock.json
  packages/grid/src/Grid.jsx
  packages/grid/src/Grid.test.jsx
  packages/grid/src/GridModel.js
  packages/grid/src/MockGridModel.js
  packages/iris-grid/jest.config.js
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/IrisGrid.test.jsx
  packages/iris-grid/src/PendingDataBottomBar.tsx
  packages/iris-grid/src/__mocks__/monaco-editor-empty.js
  packages/iris-grid/src/__mocks__/monaco-editor.js
  packages/iris-grid/src/key-handlers/ClearFilterKeyHandler.ts
  packages/iris-grid/src/key-handlers/index.ts
  packages/jsapi-shim/package-lock.json
  packages/log/package-lock.json
  packages/react-hooks/package-lock.json
Labels: bug

#57 TS Components Chunk 5
  package-lock.json
  packages/components/package.json
  packages/components/src/CustomTimeSelect.tsx
  packages/components/src/DragUtils.ts
  packages/components/src/HierarchicalCheckboxMenu.tsx
  packages/components/src/MaskedInput.jsx
  packages/components/src/MaskedInput.tsx
  packages/components/src/TimeInput.jsx
  packages/components/src/TimeInput.tsx
  packages/components/src/TimeSlider.tsx
  packages/components/src/context-actions/ContextActionUtils.ts
  packages/components/src/context-actions/ContextMenu.tsx
  packages/components/src/context-actions/index.ts
  packages/components/src/declaration.d.ts
  packages/components/src/menu-actions/DropdownMenu.tsx
  packages/components/src/menu-actions/Menu.tsx
  packages/components/src/menu-actions/index.ts
  packages/components/src/popper/index.ts
  packages/components/tsconfig.json
  packages/utils/src/TimeUtils.ts
Labels: typescript

#62 Reposition new context menu when another was open on Mac
  packages/components/src/context-actions/ContextMenuRoot.tsx
Labels: bug

#71 Implement react redux registry
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/redux/src/index.js
  packages/redux/src/reducerRegistry.ts
  packages/redux/src/reducers/index.js
  packages/redux/src/store.js
Labels: internal

#75 v0.1.3
  lerna.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package-lock.json
  packages/mocks/package.json
  packages/prettier-config/package-lock.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/tsconfig/package-lock.json
  packages/tsconfig/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal

#76 enterprise update 3
  packages/code-studio/package.json
  packages/grid/src/Grid.jsx
  packages/grid/src/Grid.test.jsx
  packages/grid/src/GridModel.js
  packages/grid/src/GridRange.js
  packages/grid/src/KeyHandler.ts
  packages/grid/src/MockGridModel.js
  packages/grid/src/errors/PasteError.ts
  packages/grid/src/errors/index.ts
  packages/grid/src/index.ts
  packages/grid/src/key-handlers/PasteKeyHandler.test.tsx
  packages/grid/src/key-handlers/PasteKeyHandler.ts
  packages/grid/src/key-handlers/index.ts
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/IrisGridProxyModel.js
  packages/iris-grid/src/IrisGridTableModel.js
  packages/iris-grid/src/PendingDataBottomBar.tsx
  packages/iris-grid/src/TableUtils.js
  packages/iris-grid/src/ToastBottomBar.tsx
  packages/iris-grid/src/filters/FilterType.js
Labels: enhancement

#81 Fix linting error from last checkin
  packages/console/src/monaco/index.js
  packages/console/src/notebook/ScriptEditor.jsx
Labels: bug

#82 Remove the testing matrix
  .github/workflows/node.js.yml
Labels: internal

#80 Fix redux "Store does not have a valid reducer" error
  packages/redux/src/index.js
  packages/redux/src/store.js
Labels: bug

#90 Fix DBDateTime formatting on Enterprise side
  packages/iris-grid/src/TableUtils.js
Labels: bug
