Repository deephaven/web-client-ui, pull requests merged in 2021-12, with the labels that each got.

#322 Add UI version to support log data
  packages/code-studio/src/log/LogExport.ts
Labels: enhancement

#324 Fix the isolated linker
  packages/dashboard-core-plugins/src/linker/Linker.tsx
  packages/dashboard-core-plugins/src/panels/ChartPanel.jsx
  packages/dashboard-core-plugins/src/panels/DropdownFilterPanel.jsx
Labels: bug, web-client-ui

#312 Enable codecov support
  .github/workflows/node.js.yml
  README.md
  codecov.yml
  jest.config.cjs
Labels: internal, web-client-ui

#328 DH-11786: Cursor inconsistent between dragging dashboard and dragging panel
  packages/dashboard/src/layout/GoldenLayout.scss
  packages/golden-layout/src/scss/goldenlayout-base.scss
  packages/grid/src/Grid.scss
Labels: bug

#330 DH-10112: Make AutoReszieTextarea explode on resize
  packages/components/src/AutoResizeTextarea.tsx
Labels: enhancement

#331 DH-11788: Enable count aggregations for non-rollups
  packages/iris-grid/src/sidebar/aggregations/AggregationUtils.ts
Labels: enhancement

#333 Fix codecov problems
  .github/workflows/node.js.yml
Labels: bug

#332 Cross column search does not restrict to selected columns
  packages/iris-grid/src/CrossColumnSearch.jsx
Labels: bug, web-client-ui

#339 Fix unit tests not running on dashboard and core-plugins packages
  packages/dashboard-core-plugins/jest.config.cjs
  packages/dashboard/jest.config.cjs
Labels: internal

#340 Fix Add to Active Notebook action
  packages/dashboard-core-plugins/src/ConsolePlugin.tsx
Labels: bug, web-client-ui

#335 Remove cursor position marker in console input bar when scrollbar is hidden
  packages/console/src/ConsoleInput.jsx
Labels: enhancement

#341 Fix Send to Active Notebook functionality
  packages/dashboard-core-plugins/src/ChartPlugin.tsx
  packages/dashboard-core-plugins/src/ConsolePlugin.tsx
  packages/dashboard-core-plugins/src/FilterPlugin.tsx
  packages/dashboard-core-plugins/src/GridPlugin.tsx
  packages/dashboard-core-plugins/src/MarkdownPlugin.tsx
  packages/dashboard-core-plugins/src/panels/FileExplorerPanel.tsx
  packages/dashboard/src/DashboardLayout.tsx
  packages/dashboard/src/DashboardPlugin.ts
  packages/dashboard/src/PanelManager.test.ts
  packages/dashboard/src/PanelManager.ts
Labels: bug, web-client-ui

#343 Version Bump v0.7.1
  .github/workflows/publish-packages.yml
  README.md
  lerna.json
  package-lock.json
  package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
Labels: internal

#345 Fix up syntax for multiple triggers
  .github/workflows/publish-packages.yml
Labels: internal

#346 Fix a couple of imports
  packages/components/src/context-actions/ContextActions.test.tsx
  packages/dashboard/src/PanelManager.ts
Labels: internal

#347 Version Bump v0.7.2
  lerna.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
Labels: internal

#342 Fix autoresizetextarea default height in Firefox
  packages/components/src/AutoResizeTextarea.tsx
Labels: bug

#337 tree table snapshots
  packages/iris-grid/src/IrisGridTreeTableModel.js
Labels: enhancement

#344 Don't trigger console csv upload overlay if dragging text
  packages/components/src/Button.tsx
  packages/console/src/Console.jsx
  packages/console/src/csv/CsvOverlay.jsx
Labels: bug

#350 fix console error message for single line errors
  packages/console/src/console-history/ConsoleHistoryResultErrorMessage.jsx
Labels: bug

#329 Better console history handling of multi-line commands
  packages/console/src/ConsoleInput.jsx
Labels: enhancement

#359 Cherry-pick plugin permissions from Enterprise
  packages/code-studio/src/main/AppInit.jsx
  packages/code-studio/src/main/AppMainContainer.jsx
  packages/code-studio/src/main/AppMainContainer.test.jsx
  packages/dashboard-core-plugins/src/index.ts
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
  packages/dashboard-core-plugins/src/prop-types/UIPropTypes.js
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.jsx
  packages/jsapi-shim/src/PropTypes.js
  packages/utils/src/TestUtils.ts
Labels: enhancement, web-client-ui, breaking

#321 freeze columns via context menu
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/IrisGridModel.js
  packages/iris-grid/src/IrisGridModelUpdater.jsx
  packages/iris-grid/src/IrisGridProxyModel.js
  packages/iris-grid/src/IrisGridTableModel.js
  packages/iris-grid/src/IrisGridUtils.js
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.jsx
Labels: enhancement

#358 Allow IrisGrid to be themeable
  packages/iris-grid/src/IrisGrid.jsx
Labels: enhancement, web-client-ui

#360 add updateFrozenColumns to mock
  packages/code-studio/src/styleguide/MockIrisGridTreeModel.js
Labels: bug

#327 Grid JS to TS conversion
  packages/code-studio/package.json
  packages/code-studio/src/styleguide/MockIrisGridTreeModel.js
  packages/code-studio/src/styleguide/MockIrisGridTreeModel.ts
  packages/grid/src/CellInputField.tsx
  packages/grid/src/EditableGridModel.ts
  packages/grid/src/EventHandlerResult.ts
  packages/grid/src/ExpandableGridModel.ts
  packages/grid/src/Grid.test.tsx
  packages/grid/src/Grid.tsx
  packages/grid/src/GridColorUtils.js
  packages/grid/src/GridColorUtils.ts
  packages/grid/src/GridMetricCalculator.ts
  packages/grid/src/GridModel.js
  packages/grid/src/GridModel.ts
  packages/grid/src/GridMouseHandler.js
  packages/grid/src/GridMouseHandler.ts
  packages/grid/src/GridRange.ts
  packages/grid/src/GridRenderer.ts
  packages/grid/src/GridUtils.test.ts
  packages/grid/src/GridUtils.ts
  packages/grid/src/KeyHandler.ts
  packages/grid/src/MockGridData.ts
  packages/grid/src/MockGridModel.js
  packages/grid/src/MockGridModel.ts
  packages/grid/src/MockTreeGridModel.js
  packages/grid/src/MockTreeGridModel.test.ts
  packages/grid/src/MockTreeGridModel.ts
  packages/grid/src/errors/AssertionError.ts
  packages/grid/src/errors/PasteError.ts
  packages/grid/src/errors/assertIsDefined.ts
  packages/grid/src/errors/index.ts
  packages/grid/src/index.ts
  packages/grid/src/key-handlers/EditKeyHandler.ts
  packages/grid/src/key-handlers/PasteKeyHandler.ts
  packages/grid/src/key-handlers/SelectionKeyHandler.ts
  packages/grid/src/key-handlers/TreeKeyHandler.ts
  packages/grid/src/memoizeClear.ts
  packages/grid/src/mouse-handlers/EditMouseHandler.ts
  packages/grid/src/mouse-handlers/GridColumnMoveMouseHandler.ts
  packages/grid/src/mouse-handlers/GridColumnSeparatorMouseHandler.js
  packages/grid/src/mouse-handlers/GridColumnSeparatorMouseHandler.ts
  packages/grid/src/mouse-handlers/GridHorizontalScrollBarMouseHandler.ts
  packages/grid/src/mouse-handlers/GridRowMoveMouseHandler.ts
  packages/grid/src/mouse-handlers/GridRowSeparatorMouseHandler.js
  packages/grid/src/mouse-handlers/GridRowSeparatorMouseHandler.ts
  packages/grid/src/mouse-handlers/GridRowTreeMouseHandler.ts
  packages/grid/src/mouse-handlers/GridScrollBarCornerMouseHandler.ts
  packages/grid/src/mouse-handlers/GridSelectionMouseHandler.ts
  packages/grid/src/mouse-handlers/GridSeparatorMouseHandler.ts
  packages/grid/src/mouse-handlers/GridVerticalScrollBarMouseHandler.ts
  packages/iris-grid/src/IrisGridModel.js
  packages/iris-grid/src/IrisGridProxyModel.js
  packages/iris-grid/src/IrisGridTableModel.js
  packages/iris-grid/src/key-handlers/ClearFilterKeyHandler.ts
  packages/iris-grid/src/key-handlers/CopyKeyHandler.ts
  packages/iris-grid/src/key-handlers/ReverseKeyHandler.ts
  packages/iris-grid/src/memoizeClear.js
  packages/log/src/LogProxy.ts
Labels: internal, web-client-ui

#361 Version bump v0.8.0
  lerna.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package-lock.json
  packages/mocks/package.json
  packages/prettier-config/package-lock.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/stylelint-config/package-lock.json
  packages/stylelint-config/package.json
  packages/tsconfig/package-lock.json
  packages/tsconfig/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal

#357 Make jsapi-shim more robust
  packages/jsapi-shim/src/dh.ts
Labels: bug

#363 Version Bump v0.8.1
  lerna.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
Labels: internal, web-client-ui

#364 Add types for JS API
  packages/babel-preset/index.js
  packages/code-studio/src/main/SessionUtils.ts
  packages/jsapi-shim/src/dh.ts
  packages/jsapi-shim/src/dh.types.ts
  packages/jsapi-shim/tsconfig.json
  packages/tsconfig/tsconfig.json
Labels: enhancement

#366 Export links and filterSets with layout
  packages/code-studio/src/main/AppMainContainer.jsx
  packages/code-studio/src/main/AppMainContainer.test.jsx
Labels: enhancement
