Repository deephaven/web-client-ui, pull requests merged in 2021-09, with the labels that each got.

#179 Update monaco-editor to 0.27.0
  packages/console/package-lock.json
  packages/console/package.json
  packages/console/src/monaco/MonacoUtils.js
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
Labels: bug, web-client-ui

#174 Make scrollbar styling consistent
  packages/components/src/BaseStyleSheet.scss
  packages/grid/src/GridRenderer.js
  packages/iris-grid/src/IrisGridTheme.js
  packages/iris-grid/src/IrisGridTheme.module.scss
Labels: enhancement

#187 Fix proxy
  packages/code-studio/.env.development
  packages/code-studio/package.json
  packages/code-studio/src/setupProxy.js
Labels: internal, web-client-ui

#186 Enable Scala syntax highlighting
  packages/code-studio/.env
  packages/code-studio/src/dashboard/panels/NotebookPanel.jsx
  packages/console/src/monaco/MonacoUtils.js
  packages/console/src/monaco/lang/scala.js
  packages/console/src/notebook/ScriptEditorUtils.js
  packages/file-explorer/src/FileUtils.ts
Labels: enhancement, notebook, web-client-ui

#195 v0.3.2
  lerna.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package-lock.json
  packages/mocks/package.json
  packages/prettier-config/package-lock.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/stylelint-config/package-lock.json
  packages/stylelint-config/package.json
  packages/tsconfig/package-lock.json
  packages/tsconfig/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal, web-client-ui

#198 Fix package-lock in golden-layout
  packages/golden-layout/package-lock.json
Labels: internal, web-client-ui, golden-layout

#199 Remove default formatting rules
  packages/code-studio/src/dashboard/LocalWorkspaceStorage.ts
  packages/iris-grid/src/Formatter.js
  packages/iris-grid/src/Formatter.test.js
Labels: bug, web-client-ui, breaking

#204 Update publish actions
  .github/workflows/publish-alpha.yml
  .github/workflows/publish-nightly.yml
  .github/workflows/publish-packages.yml
Labels: internal, web-client-ui

#209 Fix the registry used when publishing
  .github/workflows/publish-alpha.yml
  .github/workflows/publish-nightly.yml
Labels: internal, web-client-ui

#206 Fix up some issues with input tables
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/PendingDataBottomBar.tsx
Labels: web-client-ui

#210 Add registry-url back, add release action
  .github/workflows/create-release.yml
  .github/workflows/publish-alpha.yml
  .github/workflows/publish-nightly.yml
  .github/workflows/publish-packages.yml
Labels: internal, web-client-ui

#211 Remove unnecessary uses flag
  .github/workflows/create-release.yml
Labels: internal, web-client-ui

#212 fix release action
  .github/workflows/create-release.yml
Labels: internal, web-client-ui

#213 Add fetch-depth to fetch changelog properly
  .github/workflows/create-release.yml
Labels: internal, web-client-ui

#214 Specify username/email for git
  .github/workflows/create-release.yml
Labels: internal, web-client-ui

#215 Add a hyphen to fix the run step
  .github/workflows/create-release.yml
Labels: internal, web-client-ui

#216 v0.4.0
  lerna.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package-lock.json
  packages/mocks/package.json
  packages/prettier-config/package-lock.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/stylelint-config/package-lock.json
  packages/stylelint-config/package.json
  packages/tsconfig/package-lock.json
  packages/tsconfig/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal, web-client-ui

#202 Don't show custom context menu on right-click in Monaco editor
  packages/components/src/context-actions/ContextActions.tsx
  packages/console/src/Console.jsx
  packages/console/src/ConsoleInput.jsx
Labels: bug, web-client-ui

#217 Add `from-package` flag to publish step
  .github/workflows/publish-packages.yml
Labels: internal
