Repository deephaven/web-client-ui, pull requests merged in 2021-11, with the labels that each got.

#271 Fix advanced char filters
  packages/iris-grid/src/AdvancedFilterCreatorFilterItem.jsx
  packages/iris-grid/src/AdvancedFilterCreatorSelectValue.jsx
  packages/iris-grid/src/TableUtils.js
  packages/iris-grid/src/TableUtils.test.js
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.jsx
Labels: bug, web-client-ui

#265 Clean up dev/peer dependencies
  examples/component-template/README.md
  examples/component-template/package-lock.json
  examples/component-template/package.json
  package-lock.json
  package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/file-explorer/package.json
  packages/grid/package.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/log/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/utils/package.json
Labels: enhancement

#273 Add a label check action
  .github/scripts/label-check-one-of.sh
  .github/workflows/label-check-ci.yml
Labels: internal, web-client-ui

#270 Allow JS table plugins to save to workspace
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
Labels: enhancement, web-client-ui

#276 Convert base redux to TS
  packages/dashboard-core-plugins/src/linker/Linker.tsx
  packages/dashboard-core-plugins/src/panels/FileExplorerPanel.tsx
  packages/redux/package.json
  packages/redux/src/actionTypes.ts
  packages/redux/src/actions.js
  packages/redux/src/actions.ts
  packages/redux/src/index.ts
  packages/redux/src/middleware/crashReporter.ts
  packages/redux/src/middleware/index.ts
  packages/redux/src/middleware/logger.ts
  packages/redux/src/reducers/activeTool.ts
  packages/redux/src/reducers/common/index.ts
  packages/redux/src/reducers/common/mergeReducer.js
  packages/redux/src/reducers/common/mergeReducer.ts
  packages/redux/src/reducers/common/replaceByIdReducer.js
  packages/redux/src/reducers/common/replaceByIdReducer.ts
  packages/redux/src/reducers/common/replaceReducer.js
  packages/redux/src/reducers/common/replaceReducer.ts
  packages/redux/src/reducers/index.ts
  packages/redux/src/reducers/storage/commandHistoryStorage.ts
  packages/redux/src/reducers/storage/fileStorage.ts
  packages/redux/src/reducers/storage/index.ts
  packages/redux/src/reducers/storage/workspaceStorage.ts
  packages/redux/src/reducers/user.ts
  packages/redux/src/reducers/workspace.ts
  packages/redux/src/reducers/workspaceStorage.ts
  packages/redux/src/selectors.js
  packages/redux/src/selectors.ts
  packages/redux/src/store.js
  packages/redux/src/store.ts
Labels: enhancement

#279 Add extensions to direct imports from dependencies
  jest.config.base.cjs
  packages/chart/src/plotly/Plot.js
  packages/chart/src/plotly/Plotly.js
  packages/console/src/ConsoleInput.jsx
  packages/console/src/common/Code.jsx
  packages/console/src/log/LogView.jsx
  packages/console/src/monaco/MonacoCompletionProvider.jsx
  packages/console/src/monaco/MonacoCompletionProvider.test.jsx
  packages/console/src/monaco/MonacoUtils.js
  packages/console/src/notebook/Editor.jsx
  packages/console/src/notebook/ScriptEditor.jsx
  packages/iris-grid/src/sidebar/InputEditor.jsx
  packages/iris-grid/src/sidebar/TableSaver.jsx
Labels: bug

#278 Fix text truncation at very narrow widths
  packages/code-studio/src/styleguide/MockIrisGridTreeModel.js
  packages/grid/src/Grid.test.jsx
  packages/grid/src/GridRenderer.js
Labels: bug, web-client-ui

#281 Fix theme for input tables
  packages/iris-grid/src/IrisGridTheme.module.scss
Labels: bug, web-client-ui

#282 Remove load-path from sass watchers
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/file-explorer/package.json
  packages/jsapi-shim/package-lock.json
  packages/log/package-lock.json
Labels: internal

#272 DH-11632 handle LH frozen columns in the UI
  packages/code-studio/src/styleguide/MockIrisGridTreeModel.js
  packages/grid/src/GridMetricCalculator.js
  packages/grid/src/GridRenderer.js
  packages/grid/src/GridUtils.js
  packages/iris-grid/src/ColumnStatistics.jsx
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/IrisGridModel.js
  packages/iris-grid/src/IrisGridProxyModel.js
  packages/iris-grid/src/IrisGridTableModel.js
Labels: enhancement

#283 Add optional conjunction arg to TextUtil.join
  packages/utils/src/TextUtils.test.ts
  packages/utils/src/TextUtils.ts
Labels: enhancement, typescript, web-client-ui

#280 Persist shortcut definitions
  packages/code-studio/src/main/AppInit.jsx
  packages/code-studio/src/settings/ShortcutsSectionContent.tsx
  packages/components/src/shortcuts/Shortcut.ts
  packages/components/src/shortcuts/ShortcutRegistry.ts
  packages/redux/package.json
  packages/redux/src/selectors.ts
  packages/redux/src/store.ts
Labels: enhancement

#285 Ability to copy column header from ui
  packages/iris-grid/src/ColumnStatistics.jsx
  packages/iris-grid/src/ColumnStatistics.scss
  packages/iris-grid/src/mousehandlers/IrisGridColumnTooltipMouseHandler.js
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.jsx
Labels: enhancement

#287 Fix issue where tables would not reload after refreshing the page
  packages/code-studio/src/main/WidgetUtils.ts
  packages/dashboard-core-plugins/src/events/ControlEvent.js
  packages/dashboard-core-plugins/src/events/index.js
  packages/dashboard-core-plugins/src/panels/ConsolePanel.jsx
Labels: bug, web-client-ui

#288 Fix log and console crashes if process is undefined
  packages/console/src/common/ConsoleConstants.ts
  packages/log/src/DefaultLogger.js
Labels: enhancement

#291 Fix OHLC plots
  packages/chart/src/ChartUtils.js
Labels: bug, web-client-ui

#289 web v0.6.1
  lerna.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal, web-client-ui

#275 do not collapse console errors on mouseUp
  packages/console/src/console-history/ConsoleHistoryItem.scss
  packages/console/src/console-history/ConsoleHistoryResultErrorMessage.jsx
Labels: enhancement

#249 Specify required npm and node version
  .npmrc
  package.json
  packages/golden-layout/package.json
  packages/jsapi-shim/package-lock.json
  packages/log/package-lock.json
Labels: internal, web-client-ui, dependencies, golden-layout

#292 Fix panels menu not working correctly
  packages/code-studio/src/main/AppMainContainer.jsx
Labels: bug, web-client-ui

#293 fix error log white-space
  packages/console/src/console-history/ConsoleHistoryItem.scss
Labels: bug

#294 Update version to v0.6.2
  lerna.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
Labels: internal, web-client-ui

#295 Update node version to 14.x in some actions
  .github/workflows/create-release.yml
  .github/workflows/publish-alpha.yml
  .github/workflows/publish-nightly.yml
  .github/workflows/publish-packages.yml
Labels: internal, web-client-ui

#296 dependabot alerts
  examples/component-template/package.json
  package-lock.json
  package.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package-lock.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/log/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal, web-client-ui

#297 DH-11661 refresh viewport on IrisGridTableMode.handleTotalsUpdate
  packages/iris-grid/src/IrisGridTableModel.js
Labels: bug

#300 account for number of floating bottom rows in lastTop
  packages/grid/src/GridMetricCalculator.js
Labels: bug

#303 Chart fixes for docs snapshots
  packages/chart/src/ChartModelFactory.js
  packages/chart/src/ChartUtils.js
  packages/chart/src/ChartUtils.test.js
  packages/chart/src/FigureChartModel.js
  packages/chart/src/MockChartModel.js
  packages/chart/src/index.ts
  packages/chart/src/plotly/Plot.js
  packages/chart/src/plotly/Plotly.js
  packages/dashboard-core-plugins/src/panels/ConsolePanel.jsx
Labels: enhancement, breaking

#298 Enable code coverage tests, add thresholds
  jest.config.cjs
Labels: internal, web-client-ui

#310 Disable code coverage
  jest.config.cjs
Labels: internal, web-client-ui

#306 DH-11923: Fix column tooltip when above the table
  packages/code-studio/src/styleguide/MockIrisGridTreeModel.js
  packages/components/src/popper/Popper.tsx
  packages/components/src/popper/Tooltip.tsx
  packages/iris-grid/package.json
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/mousehandlers/IrisGridColumnTooltipMouseHandler.js
Labels: bug, web-client-ui

#309 Fix the nightly build
  .github/workflows/publish-nightly.yml
Labels: internal, web-client-ui

#315 Fix unusable filter set manager
  packages/dashboard-core-plugins/src/panels/FilterSetManagerPanel.jsx
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
Labels: bug

#318 Fix issue with text in numeric column filters crashing table
  packages/iris-grid/src/IrisGrid.jsx
Labels: bug

#320 Version bump v0.7.0
  lerna.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package-lock.json
  packages/mocks/package.json
  packages/prettier-config/package-lock.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/stylelint-config/package-lock.json
  packages/stylelint-config/package.json
  packages/tsconfig/package-lock.json
  packages/tsconfig/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal, web-client-ui

#319 Update DateTime reference to new package location
  __mocks__/dh-core.js
  packages/chart/src/ChartUtils.js
  packages/iris-grid/src/Formatter.test.js
  packages/iris-grid/src/TableUtils.js
  packages/iris-grid/src/TableUtils.test.js
Labels: enhancement, web-client-ui
