Repository deephaven/web-client-ui, pull requests merged in 2021-07, with the labels that each got.

#93 Clean up some publishing build steps
  examples/component-template/package.json
  package.json
  packages/file-explorer/package.json
  packages/jsapi-shim/package.json
Labels: bug

#96 v0.1.7
  lerna.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package-lock.json
  packages/mocks/package.json
  packages/prettier-config/package-lock.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/stylelint-config/package-lock.json
  packages/stylelint-config/package.json
  packages/tsconfig/package-lock.json
  packages/tsconfig/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: web-client-ui

#97 Use localStorage for workspace settings storage
  packages/code-studio/src/dashboard/LocalWorkspaceStorage.ts
  packages/code-studio/src/dashboard/WorkspaceStorage.js
  packages/code-studio/src/dashboard/WorkspaceStorage.ts
  packages/code-studio/src/main/AppInit.jsx
  packages/code-studio/src/main/AppMainContainer.test.jsx
  packages/redux/src/actions.js
Labels: enhancement, web-client-ui

#101 Add validation for renaming files
  packages/file-explorer/src/FileExistsError.ts
  packages/file-explorer/src/FileExplorer.tsx
  packages/file-explorer/src/FileList.tsx
  packages/file-explorer/src/FileListContainer.tsx
  packages/file-explorer/src/FileListItemEditor.tsx
  packages/file-explorer/src/FileNotFoundError.ts
  packages/file-explorer/src/FileStorage.ts
  packages/file-explorer/src/FileUtils.test.ts
  packages/file-explorer/src/FileUtils.ts
  packages/file-explorer/src/NewItemModal.tsx
  packages/file-explorer/src/WebdavFileStorage.ts
Labels: enhancement

#107 Fix nested context menus at index 0
  packages/components/src/context-actions/ContextMenu.tsx
Labels: bug

#100 Add dashboard layout/data saving to workspace, notebook copy
  packages/code-studio/src/dashboard/DashboardContainer.jsx
  packages/code-studio/src/dashboard/event-handlers/ConsoleEventHandler.js
  packages/code-studio/src/dashboard/event-handlers/LayoutEventHandler.js
  packages/code-studio/src/dashboard/panels/FileExplorerPanel.tsx
  packages/code-studio/src/dashboard/panels/NotebookPanel.jsx
  packages/code-studio/src/layout/LayoutUtils.js
  packages/code-studio/src/main/AppInit.jsx
  packages/code-studio/src/main/AppMainContainer.jsx
  packages/file-explorer/src/FileUtils.ts
  packages/file-explorer/src/WebdavFileStorage.ts
Labels: enhancement

#110 Fix up issues printed out when running tests
  packages/components/src/MaskedInput.tsx
  packages/components/src/context-actions/ContextActions.test.jsx
Labels: internal

#105 convert utils tests to TS
  packages/utils/src/DOMUtils.test.ts
  packages/utils/src/DbNameValidator.test.ts
  packages/utils/src/Pending.test.ts
  packages/utils/src/Pending.ts
  packages/utils/src/PromiseUtils.test.ts
  packages/utils/src/TextUtils.test.ts
  packages/utils/src/TimeUtils.test.ts
  packages/utils/src/TimeUtils.ts
Labels: internal

#113 Properly register console actions and console disconnected messages
  packages/code-studio/src/dashboard/panels/ConsolePanel.jsx
  packages/console/src/Console.jsx
  packages/console/src/ConsoleStatusBar.jsx
  packages/console/src/command-history/index.jsx
  packages/console/src/console-history/index.jsx
  packages/console/src/index.js
Labels: bug

#116 Fix import order of Bootstrap and our CSS
  package.json
  packages/code-studio/src/index.jsx
  packages/components/package.json
  packages/components/scss/custom.scss
  packages/components/src/BaseStyleSheet.scss
  packages/components/src/index.ts
Labels: bug, web-client-ui

#115 Update default port to 4000, fix up/remove parts of the readme that were incorrect
  packages/code-studio/.env.development
  packages/code-studio/README.md
Labels: internal

#126 v0.2.0
  lerna.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package-lock.json
  packages/mocks/package.json
  packages/prettier-config/package-lock.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/stylelint-config/package-lock.json
  packages/stylelint-config/package.json
  packages/tsconfig/package-lock.json
  packages/tsconfig/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: web-client-ui

#121 Add prompt when closing tab
  packages/code-studio/src/dashboard/event-handlers/ConsoleEventHandler.js
  packages/code-studio/src/dashboard/events/ConsoleEvent.js
  packages/code-studio/src/dashboard/events/TabEvent.js
  packages/code-studio/src/main/AppMainContainer.jsx
  packages/console/src/Console.test.jsx
Labels: enhancement, web-client-ui

#128 Fix disconnect status not resetting history items in Console
  packages/console/src/Console.jsx
Labels: bug, web-client-ui

#123 Convert Linker to TypeScript
  packages/code-studio/src/dashboard/linker/LinkType.js
  packages/code-studio/src/dashboard/linker/Linker.tsx
  packages/code-studio/src/dashboard/linker/LinkerLink.tsx
  packages/code-studio/src/dashboard/linker/LinkerOverlayContent.test.tsx
  packages/code-studio/src/dashboard/linker/LinkerOverlayContent.tsx
  packages/code-studio/src/dashboard/linker/LinkerUtils.tsx
  packages/iris-grid/src/formatters/DateTimeColumnFormatter.ts
  packages/iris-grid/src/formatters/TableColumnFormatter.js
  packages/iris-grid/src/formatters/TableColumnFormatter.ts
Labels: internal, web-client-ui

#109 File Explorer drag and drop to move files
  packages/code-studio/src/dashboard/panels/FileExplorerPanel.tsx
  packages/code-studio/src/dashboard/panels/NotebookPanel.jsx
  packages/code-studio/src/styleguide/Grids.jsx
  packages/code-studio/src/styleguide/MockIrisGridTreeModel.js
  packages/code-studio/src/styleguide/StyleGuideInit.jsx
  packages/components/src/DraggableItemList.tsx
  packages/components/src/ItemList.test.jsx
  packages/components/src/ItemList.test.tsx
  packages/components/src/ItemList.tsx
  packages/components/src/ItemListItem.scss
  packages/components/src/ItemListItem.tsx
  packages/components/src/SingleClickItemList.scss
  packages/components/src/SingleClickItemList.tsx
  packages/components/src/index.ts
  packages/console/src/Console.jsx
  packages/console/src/command-history/CommandHistory.jsx
  packages/console/src/command-history/CommandHistoryItem.scss
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/file-explorer/src/FileExplorer.scss
  packages/file-explorer/src/FileExplorer.tsx
  packages/file-explorer/src/FileList.scss
  packages/file-explorer/src/FileList.test.tsx
  packages/file-explorer/src/FileList.tsx
  packages/file-explorer/src/FileListContainer.tsx
  packages/file-explorer/src/FileListItemEditor.tsx
  packages/file-explorer/src/FileUtils.test.ts
  packages/file-explorer/src/FileUtils.ts
  packages/file-explorer/src/NewItemModal.tsx
  packages/file-explorer/src/WebdavFileStorage.ts
  packages/file-explorer/src/index.ts
  packages/iris-grid/src/PartitionSelectorSearch.jsx
Labels: enhancement, web-client-ui

#131 Add GitHub Publish action that executes manually with workflow_dispatch
  .github/workflows/publish-alpha.yml
Labels: internal

#120 Get console type from the API, don't allow switching language
  packages/code-studio/src/dashboard/panels/ConsolePanel.jsx
Labels: enhancement

#117 Convert components tests to typescript
  package-lock.json
  package.json
  packages/components/package.json
  packages/components/src/ComboBox.test.tsx
  packages/components/src/DragUtils.test.ts
  packages/components/src/MaskedInput.test.tsx
  packages/components/src/MaskedInput.tsx
  packages/components/src/RadioGroup.test.tsx
  packages/components/src/RadioGroup.tsx
  packages/components/src/TimeInput.test.tsx
  packages/components/src/TimeInput.tsx
  packages/components/src/TimeSlider.test.tsx
  packages/components/src/__mocks__/lodash.debounce/index.js
  packages/components/src/__mocks__/lodash.debounce/index.ts
  packages/components/src/context-actions/ContextActions.test.tsx
  packages/components/src/context-actions/ContextMenuItem.test.tsx
  packages/components/src/context-actions/__snapshots__/ContextActions.test.tsx.snap
  packages/components/src/test/eslint.test.ts
  packages/components/src/test/stylelint.test.ts
Labels: internal

#132 Update workflow_dispatch action to take a git SHA
  .github/workflows/publish-alpha.yml
Labels: internal

#135 Create a publish nightly action
  packages/code-studio/src/main/publish-nightly.yml
Labels: internal, web-client-ui

#133 Show an error message if the API is not found
  packages/code-studio/public/index.html
  packages/components/scss/new_variables.scss
  packages/iris-grid/src/AdvancedFilterCreatorSelectValueList.jsx
Labels: enhancement

#137 Disable aggregations if they're not enabled
  packages/iris-grid/src/IrisGridTableModel.js
Labels: bug

#138 Move workflow to the correct spot
  .github/workflows/publish-nightly.yml
Labels: internal, web-client-ui

#140 v0.2.1
  lerna.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package-lock.json
  packages/mocks/package.json
  packages/prettier-config/package-lock.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/stylelint-config/package-lock.json
  packages/stylelint-config/package.json
  packages/tsconfig/package-lock.json
  packages/tsconfig/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: web-client-ui
