Repository deephaven/web-client-ui, pull requests merged in 2022-06, with the labels that each got.

#601 Version Bump v0.13.1
  lerna.json
  package-lock.json
  packages/code-studio/package.json
  packages/dashboard-core-plugins/package.json
  packages/embed-grid/package.json
  packages/grid/package.json
  packages/iris-grid/package.json
Labels: internal

#603 Fix grid resizing automatically when outer parent size not specified
  packages/code-studio/src/styleguide/Grids.jsx
  packages/grid/src/Grid.scss
  packages/grid/src/Grid.tsx
Labels: bug

#604 DH-12627 Fix Aggregations formatting when only one operation on a column
  packages/iris-grid/src/IrisGridTableModel.js
Labels: bug

#588 Converted styleguide to typescript
  packages/code-studio/src/storage/WorkspaceStorage.ts
  packages/code-studio/src/styleguide/Alerts.tsx
  packages/code-studio/src/styleguide/Buttons.tsx
  packages/code-studio/src/styleguide/Charts.tsx
  packages/code-studio/src/styleguide/Colors.tsx
  packages/code-studio/src/styleguide/ContextMenus.tsx
  packages/code-studio/src/styleguide/Dialog.tsx
  packages/code-studio/src/styleguide/DraggableListInput.jsx
  packages/code-studio/src/styleguide/DraggableListInput.tsx
  packages/code-studio/src/styleguide/DraggableLists.tsx
  packages/code-studio/src/styleguide/DropdownMenus.tsx
  packages/code-studio/src/styleguide/Editors.tsx
  packages/code-studio/src/styleguide/Grids.tsx
  packages/code-studio/src/styleguide/Icons.tsx
  packages/code-studio/src/styleguide/Inputs.tsx
  packages/code-studio/src/styleguide/ItemListInput.tsx
  packages/code-studio/src/styleguide/ItemListInputs.tsx
  packages/code-studio/src/styleguide/Modals.tsx
  packages/code-studio/src/styleguide/Progress.tsx
  packages/code-studio/src/styleguide/SelectValueListInput.tsx
  packages/code-studio/src/styleguide/StyleConstants.tsx
  packages/code-studio/src/styleguide/StyleGuide.test.tsx
  packages/code-studio/src/styleguide/StyleGuide.tsx
  packages/code-studio/src/styleguide/StyleGuideInit.tsx
  packages/code-studio/src/styleguide/TimeSliderInputs.tsx
  packages/code-studio/src/styleguide/Tooltips.tsx
  packages/code-studio/src/styleguide/Typography.tsx
  packages/code-studio/tsconfig.json
  packages/components/src/ButtonOld.jsx
  packages/components/src/ButtonOld.tsx
  packages/components/src/HierarchicalCheckboxMenu.tsx
  packages/components/src/context-actions/ContextActions.tsx
  packages/components/src/index.ts
  packages/components/src/menu-actions/DropdownMenu.tsx
  packages/components/src/menu-actions/index.ts
  packages/grid/src/Grid.tsx
Labels: internal

#606 lerna 5.1.0
  package-lock.json
  package.json
Labels: internal

#607 Remove enzyme from project dependencies
  examples/component-template/README.md
  jest.setup.ts
  package-lock.json
  package.json
Labels: internal

#608 Fixed column Header not being saved in table downloads to CSV file
  packages/iris-grid/src/sidebar/TableSaver.jsx
Labels: bug

#612 Version Bump v0.13.2
  lerna.json
  package-lock.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/grid/package.json
  packages/iris-grid/package.json
Labels: internal

#613 Add support for moving ranges within grids
  packages/grid/src/GridMetrics.ts
  packages/grid/src/GridUtils.test.ts
  packages/grid/src/GridUtils.ts
Labels: enhancement

#621 update fontawesome packages
  package-lock.json
  package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/components/src/context-actions/__snapshots__/ContextActions.test.tsx.snap
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
Labels: internal, dependencies

#623 Version Bump v0.14.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal

#625 Iris grid circular dependency
  packages/iris-grid/src/IrisGridTableModel.ts
  packages/iris-grid/src/IrisGridTableModelTemplate.ts
Labels: bug

#631 iris-grid displays null instead of empty when fast scrolling for string columns
  packages/iris-grid/src/IrisGridTableModelTemplate.ts
Labels: bug

#629 Fix arrow keys not selecting next console suggestion
  packages/console/src/ConsoleInput.jsx
Labels: bug

#628 Fix grabbing scroll bar when filter bar is visible
  packages/grid/src/GridMetricCalculator.ts
  packages/grid/src/GridMetrics.ts
  packages/grid/src/mouse-handlers/GridHorizontalScrollBarMouseHandler.ts
  packages/grid/src/mouse-handlers/GridScrollBarCornerMouseHandler.ts
  packages/grid/src/mouse-handlers/GridVerticalScrollBarMouseHandler.ts
Labels: bug

#639 Fix filters in IrisGrid
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/IrisGridRenderer.ts
Labels: bug

#640 Version Bump v0.14.1
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
Labels: internal
