Repository deephaven/web-client-ui, pull requests merged in 2022-11, with the labels that each got.

#861 Fixes command history not scrolled to bottom on load
  packages/components/src/ItemList.scss
  packages/components/src/ItemList.tsx
  packages/console/src/command-history/CommandHistory.tsx
  packages/dashboard-core-plugins/src/panels/CommandHistoryPanel.tsx
Labels: bug

#860 Replaces old Deephaven logo spinner with more minimal animation
  packages/code-studio/src/styleguide/Progress.tsx
  packages/components/src/DeephavenSpinner.scss
  packages/components/src/DeephavenSpinner.tsx
  packages/components/src/index.ts
  packages/iris-grid/src/IrisGrid.scss
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/IrisGridRenderer.ts
  packages/iris-grid/src/IrisGridTheme.module.scss
Labels: enhancement

#868 Remove reference to TouchEvent
  packages/golden-layout/src/controls/DragProxy.ts
  packages/golden-layout/src/utils/DragListener.ts
Labels: bug, blocker

#870 Version Bump v0.21.1
  lerna.json
  package-lock.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/golden-layout/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/pouch-storage/package.json
Labels: internal

#869 Fix page flicker when advanced filters open
  packages/iris-grid/src/IrisGrid.tsx
Labels: bug

#797 Playwright e2e tests
  .gitignore
  README.md
  package-lock.json
  package.json
  packages/dashboard-core-plugins/src/panels/NotebookPanel.scss
  packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx
  playwright.config.ts
  tests/console.spec.ts
  tests/figure.spec.ts
  tests/figure.spec.ts-snapshots/can-open-a-simple-figure-1-chromium-darwin.png
  tests/figure.spec.ts-snapshots/can-open-a-simple-figure-1-chromium-linux.png
  tests/figure.spec.ts-snapshots/can-open-a-simple-figure-1-firefox-darwin.png
  tests/figure.spec.ts-snapshots/can-open-a-simple-figure-1-firefox-linux.png
  tests/figure.spec.ts-snapshots/can-open-a-simple-figure-1-webkit-darwin.png
  tests/figure.spec.ts-snapshots/can-open-a-simple-figure-1-webkit-linux.png
  tests/globalSetup.ts
  tests/notebook.spec.ts
  tests/table.spec.ts
  tests/table.spec.ts-snapshots/can-open-a-simple-table-1-chromium-darwin.png
  tests/table.spec.ts-snapshots/can-open-a-simple-table-1-chromium-linux.png
  tests/table.spec.ts-snapshots/can-open-a-simple-table-1-firefox-darwin.png
  tests/table.spec.ts-snapshots/can-open-a-simple-table-1-firefox-linux.png
  tests/table.spec.ts-snapshots/can-open-a-simple-table-1-webkit-darwin.png
  tests/table.spec.ts-snapshots/can-open-a-simple-table-1-webkit-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-advanced-filters-1-chromium-darwin.png
  tests/table.spec.ts-snapshots/tests-table-operations-advanced-filters-1-chromium-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-advanced-filters-1-firefox-darwin.png
  tests/table.spec.ts-snapshots/tests-table-operations-advanced-filters-1-firefox-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-advanced-filters-1-webkit-darwin.png
  tests/table.spec.ts-snapshots/tests-table-operations-advanced-filters-1-webkit-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-go-to-1-chromium-darwin.png
  tests/table.spec.ts-snapshots/tests-table-operations-go-to-1-chromium-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-go-to-1-firefox-darwin.png
  tests/table.spec.ts-snapshots/tests-table-operations-go-to-1-firefox-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-go-to-1-webkit-darwin.png
  tests/table.spec.ts-snapshots/tests-table-operations-go-to-1-webkit-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-quick-filters-with-the-advanced-filters-in-above-test-applied-1-chromium-darwin.png
  tests/table.spec.ts-snapshots/tests-table-operations-quick-filters-with-the-advanced-filters-in-above-test-applied-1-chromium-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-quick-filters-with-the-advanced-filters-in-above-test-applied-1-firefox-darwin.png
  tests/table.spec.ts-snapshots/tests-table-operations-quick-filters-with-the-advanced-filters-in-above-test-applied-1-firefox-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-quick-filters-with-the-advanced-filters-in-above-test-applied-1-webkit-darwin.png
  tests/table.spec.ts-snapshots/tests-table-operations-quick-filters-with-the-advanced-filters-in-above-test-applied-1-webkit-linux.png
  tests/utils.ts
Labels: internal

#873 Remove monaco worker from console
  package-lock.json
  packages/code-studio/package.json
  packages/code-studio/src/index.tsx
  packages/code-studio/src/styleguide/index.tsx
  packages/console/src/monaco/MonacoUtils.test.ts
  packages/console/src/monaco/MonacoUtils.ts
Labels: internal

#826 Refactor HTML buttons to Deephaven Buttons in `iris-grid` package
  packages/components/src/Button.tsx
  packages/iris-grid/src/AdvancedFilterCreator.tsx
  packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
  packages/iris-grid/src/AdvancedFilterCreatorSelectValue.tsx
  packages/iris-grid/src/ColumnStatistics.tsx
  packages/iris-grid/src/FilterInputField.tsx
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/IrisGridCopyHandler.tsx
  packages/iris-grid/src/sidebar/ChartBuilder.tsx
  packages/iris-grid/src/sidebar/CustomColumnBuilder.tsx
  packages/iris-grid/src/sidebar/CustomColumnInput.tsx
  packages/iris-grid/src/sidebar/SelectDistinctBuilder.tsx
  packages/iris-grid/src/sidebar/TableCsvExporter.tsx
  packages/iris-grid/src/sidebar/VisibilityOrderingBuilder.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingMenu.tsx
  playwright-report/index.html
Labels: internal

#881 Fix EditableItemList selection, change to multiselect
  packages/components/src/EditableItemList.test.tsx
  packages/components/src/EditableItemList.tsx
  packages/utils/src/RangeUtils.test.ts
  packages/utils/src/RangeUtils.ts
Labels: bug, breaking

#882 Cleanup unused package scripts
  package.json
  packages/chart/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/pouch-storage/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/utils/package.json
Labels: internal

#872 Fix Tab/Shift+Tab not cycling through quick filter input columns
  packages/grid/src/GridMetricCalculator.ts
  packages/iris-grid/src/IrisGrid.tsx
Labels: bug

#884 Version Bump v0.13.9
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-utils/package.json
  packages/redux/package.json
  packages/utils/package.json
Labels: internal

#890 Version Bump v0.22.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/pouch-storage/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal

#898 Persist iris grid advanced settings
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
  packages/iris-grid/src/IrisGridUtils.ts
Labels: bug

#892 Fix null in links on grouped columns
  packages/dashboard-core-plugins/src/linker/Linker.tsx
  packages/dashboard-core-plugins/src/linker/LinkerUtils.tsx
  packages/iris-grid/src/IrisGrid.test.tsx
  packages/iris-grid/src/IrisGrid.tsx
  packages/jsapi-utils/src/TableUtils.ts
Labels: bug

#900 Fix null in links on grouped columns (#892)
  packages/dashboard-core-plugins/src/linker/Linker.tsx
  packages/dashboard-core-plugins/src/linker/LinkerUtils.tsx
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/IrisGrid.test.jsx
  packages/jsapi-utils/src/TableUtils.ts
Labels: bug

#893 Added engine version to settings menu
  packages/code-studio/src/log/LogExport.ts
  packages/code-studio/src/main/AppInit.tsx
  packages/code-studio/src/main/AppMainContainer.tsx
  packages/code-studio/src/redux/selectors.ts
  packages/code-studio/src/settings/SettingsMenu.scss
  packages/code-studio/src/settings/SettingsMenu.tsx
  packages/jsapi-shim/src/dh.types.ts
  packages/redux/src/actionTypes.ts
  packages/redux/src/actions.ts
  packages/redux/src/reducers/index.ts
  packages/redux/src/reducers/serverConfigValues.ts
  packages/redux/src/store.ts
Labels: enhancement

#899 Bug fixes for enterprise silverheels
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/TreeTableViewportUpdater.tsx
  packages/iris-grid/src/sidebar/RollupRows.tsx
Labels: bug

#908 Version Bump v0.22.1
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/pouch-storage/package.json
  packages/redux/package.json
Labels: internal

#902 Dropdown menu not closing after toggle
  packages/components/src/menu-actions/DropdownMenu.tsx
  packages/components/src/menu-actions/Menu.tsx
  packages/console/src/Console.tsx
  packages/console/src/ConsoleMenu.tsx
  packages/console/src/ConsoleStatusBar.test.tsx
  packages/console/src/ConsoleStatusBar.tsx
  packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx
Labels: bug

#904 Added support for canCopy and canDownloadCsv server properties
  packages/code-studio/src/main/AppInit.tsx
Labels: enhancement

#905 Fix broken ctrl+e to clear filters shortcut (#664)
  packages/code-studio/src/main/AppMainContainer.jsx
  packages/grid/src/key-handlers/SelectionKeyHandler.ts
Labels: bug, blocker

#907 Fix Linker Esc shortcut
  packages/grid/src/key-handlers/SelectionKeyHandler.ts
Labels: bug

#910 Make MonacoCompletionProvider supply the version for textDocument (#909)
  packages/console/src/monaco/MonacoCompletionProvider.test.tsx
  packages/console/src/monaco/MonacoCompletionProvider.tsx
Labels: internal

#917 Fix Linker Esc shortcut (#907)
  packages/grid/src/key-handlers/SelectionKeyHandler.ts
Labels: bug

#915 Update github action versions to remove node 12 warning
  .github/workflows/cla.yml
  .github/workflows/create-release.yml
  .github/workflows/label-check-ci.yml
  .github/workflows/node.js.yml
  .github/workflows/publish-alpha.yml
  .github/workflows/publish-nightly.yml
  .github/workflows/publish-packages.yml
Labels: internal

#911 Fix console error that is logged about NaN when running tests
  packages/console/src/Console.test.tsx
Labels: bug
