Repository deephaven/web-client-ui, pull requests merged in 2022-10, with the labels that each got.

#787 gRPC file storage
  __mocks__/dh-core.js
  package-lock.json
  packages/code-studio/package.json
  packages/code-studio/src/main/AppInit.tsx
  packages/code-studio/src/main/SessionUtils.ts
  packages/code-studio/src/storage/LocalWorkspaceStorage.ts
  packages/code-studio/src/storage/WebdavLayoutStorage.ts
  packages/code-studio/src/storage/grpc/GrpcFileStorage.ts
  packages/code-studio/src/storage/grpc/GrpcFileStorageTable.test.ts
  packages/code-studio/src/storage/grpc/GrpcFileStorageTable.ts
  packages/code-studio/src/storage/grpc/GrpcLayoutStorage.ts
  packages/file-explorer/README.md
  packages/file-explorer/package.json
  packages/file-explorer/src/FileUtils.ts
  packages/file-explorer/src/WebdavFileStorage.ts
  packages/file-explorer/src/WebdavFileStorageTable.test.ts
  packages/file-explorer/src/index.ts
  packages/jsapi-shim/src/dh.types.ts
Labels: enhancement, notable

#782 File explorer path and display initializes from focused dir/file instead of root
  packages/code-studio/src/storage/grpc/GrpcFileStorageTable.ts
  packages/dashboard-core-plugins/src/panels/FileExplorerPanel.test.tsx
  packages/dashboard-core-plugins/src/panels/MockFileStorageTable.ts
  packages/file-explorer/src/FileExplorer.tsx
  packages/file-explorer/src/FileList.tsx
  packages/file-explorer/src/FileListContainer.tsx
  packages/file-explorer/src/FileStorage.ts
  packages/file-explorer/src/NewItemModal.tsx
Labels: enhancement, breaking

#789 Version Bump v0.19.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal

#791 Allow up to 1% drop in code coverage per commit
  codecov.yml
Labels: internal

#801 Add NotebookPanel hydration function
  packages/dashboard-core-plugins/src/ConsolePlugin.tsx
Labels: bug

#802 Version Bump v0.19.1
  lerna.json
  package-lock.json
  packages/code-studio/package.json
  packages/dashboard-core-plugins/package.json
Labels: internal

#799 Set aria-label for icon only buttons
  packages/components/src/Button.tsx
Labels: enhancement

#793 Change Boostrap px-2 to separate custom-px-2 class for icon only buttons
  packages/components/scss/BaseStyleSheet.scss
  packages/components/src/Button.tsx
Labels: enhancement

#794 Catch and display errors in downloading in the `TableCsvExporter` component
  packages/iris-grid/src/IrisGridTestUtils.ts
  packages/iris-grid/src/sidebar/TableCsvExporter.test.tsx
  packages/iris-grid/src/sidebar/TableCsvExporter.tsx
Labels: bug

#808 Update to use new $GITHUB_OUTPUT instead of set-output
  .github/workflows/publish-nightly.yml
Labels: internal

#809 Print app information to the log
  packages/code-studio/src/main/AppInit.tsx
Labels: internal

#810 790 file explorer render fail
  packages/chart/src/FigureChartModel.ts
  packages/code-studio/src/storage/grpc/GrpcFileStorageTable.test.ts
  packages/code-studio/src/storage/grpc/GrpcFileStorageTable.ts
  packages/dashboard-core-plugins/src/panels/FileExplorerPanel.test.tsx
  packages/file-explorer/src/FileStorage.ts
  packages/file-explorer/src/NewItemModal.tsx
Labels: bug, breaking

#816 Fix eslint errors in TableInput
  packages/jsapi-components/src/TableInput.tsx
Labels: internal, blocker

#814 Re-enable strictLibCheck
  tsconfig.json
Labels: bug

#811 Refactor <button> to <Button> in NewItemModal
  packages/file-explorer/src/NewItemModal.tsx
Labels: internal

#830 Version Bump v0.13.8
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-utils/package.json
  packages/redux/package.json
Labels: internal

#822 Refactor HTML buttons in `code-studio` to Deephaven Buttons
  packages/code-studio/src/main/AppMainContainer.tsx
  packages/code-studio/src/main/WidgetList.tsx
  packages/code-studio/src/plugins/internal/ExamplePlugin.jsx
  packages/code-studio/src/settings/FormattingSectionContent.tsx
  packages/code-studio/src/settings/LegalNotice.tsx
  packages/code-studio/src/settings/SettingsMenu.tsx
  packages/code-studio/src/settings/SettingsMenuSection.tsx
  packages/code-studio/src/styleguide/ContextMenus.tsx
  packages/code-studio/src/styleguide/Dialog.tsx
  packages/code-studio/src/styleguide/DropdownMenus.tsx
  packages/code-studio/src/styleguide/Modals.tsx
  packages/code-studio/src/styleguide/Progress.tsx
  packages/code-studio/src/styleguide/Tooltips.tsx
  packages/components/src/Button.tsx
Labels: internal

#828 Delete the component template
  README.md
  examples/component-template/.gitignore
  examples/component-template/README.md
  examples/component-template/jest.config.cjs
  examples/component-template/package.json
  examples/component-template/src/ExampleComponent.scss
  examples/component-template/src/ExampleComponent.test.tsx
  examples/component-template/src/ExampleComponent.tsx
  examples/component-template/src/ExampleJsComponent.jsx
  examples/component-template/src/ExampleTest.test.ts
  examples/component-template/src/__mocks__/fileMock.js
  examples/component-template/src/index.ts
  examples/component-template/src/test/eslint.test.js
  examples/component-template/src/test/stylelint.test.js
  examples/component-template/tsconfig.json
Labels: internal

#831 Fix keyboard shortcuts not working in Grid
  packages/components/src/context-actions/ContextActionUtils.ts
  packages/components/src/context-actions/ContextActions.tsx
Labels: bug

#823 Refactor HTML buttons to Deephaven Buttons in `components`, `console`, and `dashboard-core-plugins` packages
  packages/components/src/BasicModal.tsx
  packages/components/src/HierarchicalCheckboxMenu.tsx
  packages/components/src/navigation/Page.tsx
  packages/console/src/ConsoleMenu.tsx
  packages/console/src/csv/CsvInputBar.tsx
  packages/console/src/csv/CsvOverlay.tsx
  packages/console/src/log/LogView.tsx
  packages/dashboard-core-plugins/src/controls/dropdown-filter/DropdownFilter.tsx
  packages/dashboard-core-plugins/src/controls/input-filter/InputFilter.tsx
  packages/dashboard-core-plugins/src/controls/markdown/MarkdownStartPage.tsx
  packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.tsx
  packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx
  packages/dashboard-core-plugins/src/panels/PandasPanel.tsx
  packages/dashboard-core-plugins/src/panels/RenameDialog.tsx
Labels: internal

#835 Fix context menu not showing on Grid
  packages/grid/src/Grid.tsx
Labels: bug

#837 Version Bump v0.20.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal

#818 Extract PouchDB storage into @deephaven/pouch-storage package
  package-lock.json
  packages/code-studio/package.json
  packages/code-studio/src/main/AppInit.tsx
  packages/code-studio/tsconfig.json
  packages/pouch-storage/.gitignore
  packages/pouch-storage/README.md
  packages/pouch-storage/jest.config.cjs
  packages/pouch-storage/package.json
  packages/pouch-storage/src/PouchCommandHistoryStorage.ts
  packages/pouch-storage/src/PouchCommandHistoryTable.ts
  packages/pouch-storage/src/PouchStorageTable.ts
  packages/pouch-storage/src/index.ts
  packages/pouch-storage/tsconfig.json
  tsconfig.json
Labels: internal

#842 Fix new notebooks not saving when first created
  packages/code-studio/src/storage/grpc/GrpcFileStorage.ts
Labels: bug

#840 Disable line numbers in Log Panel
  packages/console/src/log/LogView.tsx
Labels: bug

#844 resolve missing onclick proptype validation
  packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx
Labels: bug

#849 Added function `close` to `interface IdeSession` in `dh.type`
  packages/jsapi-shim/src/dh.types.ts
Labels: internal

#846 Fix dependency path typo breaking the DHE installation
  package-lock.json
  packages/dashboard/package.json
Labels: internal, blocker

#838 Add scientific notation number format option to table context menu
  packages/iris-grid/src/format-context-menus/DecimalFormatContextMenu.ts
  packages/iris-grid/src/format-context-menus/IntegerFormatContextMenu.ts
  packages/jsapi-utils/src/formatters/DecimalColumnFormatter.ts
  packages/jsapi-utils/src/formatters/IntegerColumnFormatter.ts
Labels: enhancement

#848 Fix incorrect table sizes in panel tab tooltip
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
  packages/iris-grid/src/IrisGridModel.ts
  packages/iris-grid/src/IrisGridTableModelTemplate.ts
Labels: bug

#854 Revert "Fix incorrect table sizes in panel tab tooltip"
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
  packages/iris-grid/src/IrisGridModel.ts
  packages/iris-grid/src/IrisGridTableModelTemplate.ts
Labels: bug

#851 DH-13511 Ignore empty Editable List input
  packages/components/src/EditableItemList.test.tsx
  packages/components/src/EditableItemList.tsx
Labels: bug

#853 Fix default formatting rule always showing empty error
  packages/code-studio/src/settings/FormattingSectionContent.tsx
Labels: bug

#855 Fix incorrect table sizes in panel tab tooltip
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
  packages/dashboard-core-plugins/src/panels/IrisGridPanelTooltip.tsx
Labels: bug

#857 DH-13511 Ignore empty EditableList input
  packages/components/src/EditableItemList.test.tsx
  packages/components/src/EditableItemList.tsx
Labels: internal

#856 DH-13548 Fix DateTimeInputs missing nanos
  packages/components/src/DateTimeInput.test.tsx
  packages/components/src/DateTimeInput.tsx
Labels: enhancement

#863 Add missing exports and fix CSS for DHE
  packages/components/.gitignore
  packages/components/package.json
  packages/components/scss/BaseStyleSheet.scss
  packages/components/scss/custom.scss
  packages/components/scss/custom_vite.scss
  packages/console/src/index.ts
  packages/iris-grid/src/index.ts
  packages/iris-grid/src/sidebar/index.ts
  packages/jsapi-shim/src/index.ts
Labels: internal

#858 DH-13577 Subplots
  __mocks__/dh-core.js
  packages/chart/src/ChartUtils.test.ts
  packages/chart/src/ChartUtils.ts
  packages/chart/src/FigureChartModel.ts
  packages/jsapi-shim/src/dh.types.ts
Labels: enhancement

#865 Version Bump v0.21.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/pouch-storage/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal
