Repository deephaven/web-client-ui, pull requests merged in 2022-02, with the labels that each got.

#414 Fix pouchdb deprecation warning when starting up UI
  packages/code-studio/src/storage/PouchStorageTable.ts
Labels: internal, web-client-ui

#413 Fix up Dashboard Plugin props
  packages/dashboard-core-plugins/src/ChartPlugin.tsx
  packages/dashboard-core-plugins/src/ConsolePlugin.tsx
  packages/dashboard-core-plugins/src/FilterPlugin.tsx
  packages/dashboard-core-plugins/src/GridPlugin.tsx
  packages/dashboard-core-plugins/src/LinkerPlugin.tsx
  packages/dashboard-core-plugins/src/MarkdownPlugin.tsx
  packages/dashboard-core-plugins/src/PandasPlugin.tsx
  packages/dashboard-core-plugins/src/index.test.tsx
  packages/dashboard/src/DashboardPlugin.ts
  packages/iris-grid/src/index.ts
  packages/mocks/src/golden-layout.js
  packages/redux/src/createMockStore.ts
  packages/redux/src/index.ts
Labels: bug, web-client-ui, breaking

#418 Fast refresh fix
  packages/code-studio/package.json
Labels: internal

#417 Fix File Explorer causing scrollbars to appear
  packages/file-explorer/src/FileExplorerToolbar.scss
Labels: bug, web-client-ui

#420 Fix double box-shadow focus ring on iconOnly ghost buttons
  packages/components/src/BaseStyleSheet.scss
  packages/embed-grid/package.json
Labels: bug

#419 Fix irisgrid tooltip state tracking
  packages/components/src/popper/Popper.tsx
  packages/components/src/popper/Tooltip.tsx
  packages/iris-grid/src/IrisGrid.jsx
Labels: bug

#422 Fix active filter set after edit
  packages/dashboard-core-plugins/src/panels/FilterSetManager.tsx
  packages/dashboard-core-plugins/src/panels/FilterSetManagerPanel.jsx
Labels: bug, web-client-ui

#421 Fix the objects not being loaded with console
  packages/console/src/Console.jsx
  packages/dashboard-core-plugins/src/panels/ConsolePanel.jsx
Labels: bug

#423 DH-10241: Persist grid isStuckToBottom state
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
  packages/grid/src/Grid.tsx
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/IrisGridUtils.js
Labels: enhancement, web-client-ui

#404 DH-12099 IrisGrid canToggleSearch should allow override by layoutHints
  __mocks__/dh-core.js
  packages/iris-grid/src/IrisGrid.jsx
Labels: enhancement

#427 Improve command history tooltip layout
  packages/components/src/popper/Popper.tsx
  packages/components/src/popper/Tooltip.tsx
  packages/console/src/command-history/CommandHistoryItemTooltip.jsx
  packages/console/src/command-history/CommandHistoryItemTooltip.scss
Labels: bug

#429 Fix uncaught error from #404
  __mocks__/dh-core.js
  packages/iris-grid/src/IrisGrid.jsx
Labels: bug

#428 DH-10115: add temporary success state to save custom column button
  packages/iris-grid/src/sidebar/CustomColumnBuilder.jsx
Labels: enhancement

#433 Web v0.9.2
  lerna.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/embed-grid/package-lock.json
  packages/embed-grid/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/mocks/package-lock.json
  packages/mocks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
Labels: internal, web-client-ui

#434 Change GitHub actions to use `npm ci` instead of `npm install`
  .github/workflows/publish-alpha.yml
  .github/workflows/publish-nightly.yml
  .github/workflows/publish-packages.yml
Labels: internal

#435 Pin the fontawesome deps
  package-lock.json
  package.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/embed-grid/package-lock.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/icons/package.json
Labels: internal, web-client-ui

#436 Version Bump v0.9.3
  README.md
  lerna.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/embed-grid/package-lock.json
  packages/embed-grid/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
Labels: internal, web-client-ui

#411 upgrade react to v17
  examples/component-template/package.json
  jest.setup.js
  package-lock.json
  package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/embed-grid/package-lock.json
  packages/embed-grid/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
Labels: internal, web-client-ui, dependencies, breaking

#441 Fix table row color darken for depth 0
  packages/grid/src/GridColorUtils.ts
Labels: bug

#442 Support BigDecimal and BigInteger in formatting of numbers.
  packages/iris-grid/src/TableUtils.ts
Labels: documentation

#439 Fix layout import/export, add tests
  package-lock.json
  packages/code-studio/src/main/AppInit.jsx
  packages/code-studio/src/main/AppMainContainer.jsx
  packages/code-studio/src/main/AppMainContainer.test.jsx
  packages/code-studio/src/main/LayoutStorage.ts
  packages/code-studio/src/main/UserLayoutUtils.test.ts
  packages/code-studio/src/main/UserLayoutUtils.ts
  packages/code-studio/src/main/WebdavLayoutStorage.ts
Labels: bug, web-client-ui

#443 feb dependabot alerts
  package-lock.json
  package.json
  packages/chart/src/Chart.scss
  packages/components/src/BaseStyleSheet.scss
  packages/components/src/SearchInput.scss
  packages/dashboard-core-plugins/src/panels/FilterSetManagerPanel.scss
  packages/dashboard-core-plugins/src/panels/MarkdownNotebook.scss
  packages/embed-grid/src/index.scss
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/stylelint-config/index.js
  packages/stylelint-config/package.json
Labels: internal, web-client-ui

#448 Version Bump v0.10.0
  lerna.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/embed-grid/package-lock.json
  packages/embed-grid/package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package-lock.json
  packages/mocks/package.json
  packages/prettier-config/package-lock.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/stylelint-config/package-lock.json
  packages/stylelint-config/package.json
  packages/tsconfig/package-lock.json
  packages/tsconfig/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal, web-client-ui

#409 Conditional formatting
  package-lock.json
  packages/code-studio/src/styleguide/MockIrisGridTreeModel.ts
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/IrisGridModel.ts
  packages/iris-grid/src/IrisGridModelUpdater.jsx
  packages/iris-grid/src/IrisGridModelUpdater.tsx
  packages/iris-grid/src/IrisGridProxyModel.js
  packages/iris-grid/src/IrisGridTableModel.js
  packages/iris-grid/src/IrisGridUtils.js
  packages/iris-grid/src/sidebar/OptionType.ts
  packages/iris-grid/src/sidebar/conditional-formatting/ColumnFormatEditor.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionEditor.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormatEditor.scss
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormatEditor.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingAPIUtils.ts
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingMenu.scss
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingMenu.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.test.ts
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.ts
  packages/iris-grid/src/sidebar/conditional-formatting/RowFormatEditor.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/StyleEditor.scss
  packages/iris-grid/src/sidebar/conditional-formatting/StyleEditor.tsx
  packages/iris-grid/src/sidebar/icons/FormatColumnWhereIcon.svg
  packages/iris-grid/src/sidebar/icons/FormatColumnWhereIcon.tsx
  packages/iris-grid/src/sidebar/icons/FormatRowWhereIcon.svg
  packages/iris-grid/src/sidebar/icons/FormatRowWhereIcon.tsx
  packages/iris-grid/src/sidebar/icons/index.js
  packages/jsapi-shim/src/dh.types.ts
Labels: enhancement, web-client-ui

#432 JS plugins loading from the server
  packages/chart/package-lock.json
  packages/chart/src/Chart.jsx
  packages/chart/src/ChartModelFactory.js
  packages/chart/src/ChartUtils.js
  packages/code-studio/.env
  packages/code-studio/.env.development
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/code-studio/src/main/App.jsx
  packages/code-studio/src/main/AppInit.jsx
  packages/code-studio/src/main/AppMainContainer.jsx
  packages/code-studio/src/main/AppMainContainer.test.jsx
  packages/code-studio/src/main/WidgetList.tsx
  packages/code-studio/src/main/WidgetUtils.ts
  packages/code-studio/src/plugins/PluginUtils.jsx
  packages/code-studio/src/plugins/loadRemoteModule.js
  packages/code-studio/src/remote-component.config.js
  packages/console/package-lock.json
  packages/console/src/Console.jsx
  packages/console/src/console-history/ConsoleHistoryItem.jsx
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/src/ChartBuilderPlugin.tsx
  packages/dashboard-core-plugins/src/ChartPlugin.tsx
  packages/dashboard-core-plugins/src/GridPlugin.tsx
  packages/dashboard-core-plugins/src/PandasPlugin.tsx
  packages/dashboard-core-plugins/src/events/ChartEvent.js
  packages/dashboard-core-plugins/src/events/IrisGridEvent.js
  packages/dashboard-core-plugins/src/events/PandasEvent.js
  packages/dashboard-core-plugins/src/index.test.tsx
  packages/dashboard-core-plugins/src/index.ts
  packages/dashboard-core-plugins/src/panels/ConsolePanel.jsx
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
  packages/dashboard/package-lock.json
  packages/dashboard/src/Dashboard.tsx
  packages/dashboard/src/DashboardLayout.tsx
  packages/dashboard/src/PanelEvent.js
  packages/dashboard/src/PanelManager.ts
  packages/file-explorer/package-lock.json
  packages/grid/package-lock.json
  packages/icons/package-lock.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/IrisGridModelFactory.js
  packages/iris-grid/src/sidebar/ChartBuilder.jsx
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/src/dh.types.ts
  packages/log/package-lock.json
  packages/react-hooks/package-lock.json
  packages/redux/package-lock.json
  packages/redux/src/actionTypes.ts
  packages/redux/src/actions.ts
  packages/redux/src/reducers/index.ts
  packages/redux/src/reducers/plugins.ts
  packages/redux/src/selectors.ts
  packages/redux/src/store.ts
  packages/storage/package-lock.json
  packages/utils/package-lock.json
Labels: enhancement, web-client-ui, breaking

#451 Version Bump v0.11.0
  lerna.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/embed-grid/package-lock.json
  packages/embed-grid/package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package-lock.json
  packages/mocks/package.json
  packages/prettier-config/package-lock.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/stylelint-config/package-lock.json
  packages/stylelint-config/package.json
  packages/tsconfig/package-lock.json
  packages/tsconfig/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal, web-client-ui

#455 Update @deephaven/grid README with some examples
  package-lock.json
  packages/code-studio/src/styleguide/Grids.jsx
  packages/code-studio/src/styleguide/grid-examples/AsyncExample.jsx
  packages/code-studio/src/styleguide/grid-examples/QuadrillionExample.jsx
  packages/code-studio/src/styleguide/grid-examples/StaticExample.jsx
  packages/code-studio/src/styleguide/grid-examples/TreeExample.jsx
  packages/grid/README.md
  packages/grid/src/StaticDataGridModel.test.ts
  packages/grid/src/StaticDataGridModel.ts
  packages/grid/src/ViewportDataGridModel.ts
  packages/grid/src/index.ts
Labels: documentation, web-client-ui

#456 Version Bump v0.11.1
  lerna.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/embed-grid/package-lock.json
  packages/embed-grid/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
Labels: internal, web-client-ui
