Repository deephaven/web-client-ui, pull requests merged in 2022-05, with the labels that each got.

#533 Update README with some onboarding updates, contributing instructions
  .github/workflows/cla.yml
  README.md
  packages/code-studio/README.md
Labels: internal

#534 Fix column tooltip not repositioning correctly when resizing columns
  packages/iris-grid/src/IrisGrid.jsx
Labels: bug

#544 Fix cell overflow button overlapping scroll bar and not truncating text with row header
  packages/iris-grid/src/IrisGridRenderer.js
Labels: bug

#551 Version Bump v0.11.8
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/embed-grid/package.json
  packages/iris-grid/package.json
Labels: internal

#550 Added data-testid
  .vscode/settings.json
  packages/components/src/AutoCompleteInput.tsx
  packages/components/src/AutoResizeTextarea.tsx
  packages/components/src/BasicModal.tsx
  packages/components/src/ButtonGroup.tsx
  packages/components/src/CardFlip.tsx
  packages/components/src/Checkbox.tsx
  packages/components/src/Collapse.tsx
  packages/components/src/ComboBox.tsx
  packages/components/src/CustomTimeSelect.tsx
  packages/components/src/DebouncedSearchInput.tsx
  packages/components/src/DeephavenSpinner.tsx
  packages/components/src/DraggableItemList.tsx
  packages/components/src/HierarchicalCheckboxMenu.tsx
  packages/components/src/ItemList.tsx
  packages/components/src/ItemListItem.tsx
  packages/components/src/LoadingOverlay.tsx
  packages/components/src/LoadingSpinner.tsx
  packages/components/src/MaskedInput.tsx
  packages/components/src/Option.tsx
  packages/components/src/RadioGroup.tsx
  packages/components/src/SearchInput.tsx
  packages/components/src/Select.tsx
  packages/components/src/SelectValueList.tsx
  packages/components/src/SocketedButton.tsx
  packages/components/src/TimeInput.tsx
  packages/components/src/TimeSlider.tsx
  packages/components/src/ToastNotification.tsx
  packages/components/src/UISwitch.test.tsx
  packages/components/src/UISwitch.tsx
  packages/components/src/context-actions/ContextActions.tsx
  packages/components/src/context-actions/ContextMenu.tsx
  packages/components/src/context-actions/ContextMenuItem.tsx
  packages/components/src/context-actions/ContextMenuRoot.tsx
  packages/components/src/context-actions/GlobalContextActions.tsx
  packages/components/src/menu-actions/DropdownMenu.tsx
  packages/components/src/menu-actions/Menu.tsx
  packages/components/src/navigation/Menu.tsx
  packages/components/src/navigation/MenuItem.tsx
  packages/components/src/navigation/Page.tsx
  packages/components/src/navigation/Stack.tsx
  packages/components/src/popper/Popper.tsx
  packages/components/src/popper/Tooltip.tsx
Labels: enhancement

#543 DH-10111 Fix missing horizontal scroll bar for single column tables
  packages/grid/src/Grid.tsx
  packages/grid/src/GridMetricCalculator.ts
  packages/grid/src/GridMetrics.ts
  packages/grid/src/mouse-handlers/GridHorizontalScrollBarMouseHandler.ts
  packages/grid/src/mouse-handlers/GridVerticalScrollBarMouseHandler.ts
Labels: bug

#559 Version Bump web-v0.11.9
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/dashboard-core-plugins/package.json
  packages/embed-grid/package.json
  packages/grid/package.json
  packages/iris-grid/package.json
Labels: internal

#553 Replace anonymous useEffect functions with named functions
  packages/code-studio/src/main/AppControlsMenu.jsx
  packages/code-studio/src/main/AppInit.jsx
  packages/code-studio/src/settings/ShortcutItem.tsx
  packages/code-studio/src/styleguide/Icons.jsx
  packages/code-studio/src/styleguide/Navigations.tsx
  packages/code-studio/src/styleguide/grid-examples/AsyncExample.jsx
  packages/components/src/AutoResizeTextarea.tsx
  packages/components/src/CardFlip.tsx
  packages/components/src/Checkbox.tsx
  packages/components/src/MaskedInput.tsx
  packages/components/src/TimeInput.tsx
  packages/components/src/TimeSlider.tsx
  packages/components/src/navigation/Stack.tsx
  packages/console/src/command-history/CommandHistoryViewportUpdater.tsx
  packages/dashboard-core-plugins/src/ChartPlugin.tsx
  packages/dashboard-core-plugins/src/ConsolePlugin.tsx
  packages/dashboard-core-plugins/src/FilterPlugin.tsx
  packages/dashboard-core-plugins/src/GridPlugin.tsx
  packages/dashboard-core-plugins/src/MarkdownPlugin.tsx
  packages/dashboard-core-plugins/src/PandasPlugin.tsx
  packages/dashboard/src/Dashboard.tsx
  packages/dashboard/src/DashboardLayout.tsx
  packages/dashboard/src/layout/hooks.ts
  packages/embed-grid/src/App.tsx
  packages/eslint-config/index.js
  packages/file-explorer/src/FileExplorer.tsx
  packages/file-explorer/src/FileList.tsx
  packages/file-explorer/src/FileListItemEditor.tsx
  packages/grid/src/CellInputField.tsx
  packages/icons/docs/app-helpers.js
  packages/iris-grid/src/IrisGridCellOverflowModal.tsx
  packages/iris-grid/src/IrisGridModelUpdater.tsx
  packages/iris-grid/src/PendingDataBottomBar.tsx
  packages/iris-grid/src/sidebar/aggregations/Aggregations.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/ColumnFormatEditor.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionEditor.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/RowFormatEditor.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/StyleEditor.tsx
  packages/react-hooks/src/useForwardedRef.ts
  packages/react-hooks/src/usePrevious.ts
  packages/storage/src/StorageTableViewportUpdater.ts
Labels: enhancement

#548 Remove dependency on jszip from @deephaven/console
  package-lock.json
  packages/code-studio/src/main/AppMainContainer.jsx
  packages/console/package.json
  packages/console/src/Console.jsx
  packages/console/src/csv/CsvInputBar.jsx
  packages/console/src/csv/CsvOverlay.jsx
  packages/console/src/csv/CsvOverlay.test.jsx
  packages/dashboard-core-plugins/src/ConsolePlugin.tsx
  packages/dashboard-core-plugins/src/panels/ConsolePanel.jsx
Labels: internal, breaking

#565 remove enzyme code studio and replace with react-testing-library
  packages/code-studio/src/main/AppMainContainer.jsx
  packages/code-studio/src/main/AppMainContainer.test.jsx
Labels: enhancement

#574 Use session type provided by the server instead of hardcoding python
  packages/embed-grid/src/App.tsx
Labels: bug

#571 Don't scroll columns into view on click
  packages/grid/src/mouse-handlers/GridSelectionMouseHandler.ts
Labels: enhancement, grid

#569 Fix invalid format custom columns created from row formats based on different columns
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.test.ts
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.ts
Labels: bug, web-client-ui, grid

#578 web v0.12.0
  examples/component-template/package.json
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal

#575 Fix floating column border not touching top and bottom
  packages/grid/src/GridRenderer.ts
Labels: bug

#568 remove enzyme from components
  packages/components/src/ComboBox.test.tsx
  packages/components/src/ItemList.test.tsx
  packages/components/src/MaskedInput.test.tsx
  packages/components/src/RadioGroup.test.tsx
  packages/components/src/TimeInput.test.tsx
  packages/components/src/TimeSlider.test.tsx
  packages/components/src/context-actions/ContextMenuItem.test.tsx
  packages/components/src/navigation/MenuItem.test.tsx
  packages/components/src/navigation/Stack.test.tsx
Labels: internal

#580 DH-11788 Fix aggregation formatting when only one aggregation is applied
  packages/iris-grid/src/IrisGridTableModel.js
Labels: bug

#583 Improved clipboard write handling
  packages/components/src/context-actions/ContextActionUtils.ts
Labels: enhancement

#577 Remove enzyme from all packages
  packages/components/src/RadioGroup.test.tsx
  packages/console/src/Console.test.jsx
  packages/console/src/command-history/CommandHistory.test.jsx
  packages/console/src/command-history/CommandHistoryActions.test.jsx
  packages/console/src/command-history/CommandHistoryItemTooltip.test.jsx
  packages/console/src/monaco/MonacoCompletionProvider.test.jsx
  packages/dashboard-core-plugins/src/index.test.tsx
  packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.test.tsx
  packages/dashboard-core-plugins/src/panels/ChartPanel.test.jsx
  packages/dashboard-core-plugins/src/panels/ConsolePanel.jsx
  packages/dashboard-core-plugins/src/panels/ConsolePanel.test.jsx
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.test.jsx
  packages/dashboard-core-plugins/src/panels/MarkdownPanel.test.jsx
  packages/dashboard-core-plugins/src/panels/PanelContextMenu.test.jsx
  packages/dashboard/src/Dashboard.test.tsx
  packages/iris-grid/src/AdvancedFilterCreator.test.jsx
  packages/iris-grid/src/IrisGridCopyHandler.test.jsx
  packages/iris-grid/src/IrisGridPartitionSelector.test.jsx
  packages/iris-grid/src/PartitionSelectorSearch.test.jsx
  packages/iris-grid/src/TableViewportUpdater.test.jsx
  packages/iris-grid/src/sidebar/aggregations/AggregationEdit.test.tsx
  packages/iris-grid/src/sidebar/aggregations/Aggregations.test.tsx
Labels: internal

#566 Fix various layout hint issues
  packages/grid/src/mouse-handlers/GridColumnMoveMouseHandler.ts
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/IrisGridModel.ts
  packages/iris-grid/src/IrisGridProxyModel.js
  packages/iris-grid/src/IrisGridTableModel.js
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.jsx
Labels: bug

#594 Listen for click instead of mousedown on golden layout Tabs
  packages/golden-layout/src/js/controls/Tab.js
Labels: bug

#591 Remove @deephaven peer dependencies
  package-lock.json
  packages/chart/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/file-explorer/package.json
  packages/iris-grid/package.json
  packages/redux/package.json
  packages/storage/package.json
Labels: internal

#595 Version Bump v0.13.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal
