Repository deephaven/web-client-ui, pull requests merged in 2022-12, with the labels that each got.

#916 Subtract the pending row count when displaying row count
  packages/dashboard-core-plugins/src/panels/IrisGridPanelTooltip.tsx
  packages/iris-grid/src/ColumnStatistics.tsx
Labels: bug

#923 Version Bump v0.22.2
  lerna.json
  package-lock.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/grid/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/pouch-storage/package.json
Labels: internal

#924 Stringify the error details before outputting to console
  packages/code-studio/src/main/AppInit.tsx
Labels: bug

#925 Version bump 0.13.10
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/grid/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-utils/package.json
  packages/redux/package.json
Labels: internal

#914 Clean up non-semantic uses of defined colours
  packages/chart/src/Chart.scss
  packages/chart/src/ChartTheme.module.scss
  packages/code-studio/src/settings/SettingsMenu.scss
  packages/components/scss/BaseStyleSheet.scss
  packages/components/scss/bootstrap_overrides.scss
  packages/components/src/ThemeExport.module.scss
  packages/console/src/command-history/CommandHistoryItem.scss
  packages/console/src/log/LogLevelMenuItem.scss
  packages/console/src/monaco/MonacoTheme.module.scss
  packages/dashboard-core-plugins/src/controls/dropdown-filter/DropdownFilter.scss
  packages/dashboard-core-plugins/src/controls/input-filter/InputFilter.scss
  packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.scss
  packages/dashboard-core-plugins/src/panels/FilterSetManager.scss
  packages/dashboard-core-plugins/src/panels/MarkdownNotebook.scss
  packages/dashboard-core-plugins/src/panels/NotebookPanel.scss
  packages/file-explorer/src/FileListItemEditor.scss
  packages/iris-grid/src/AdvancedFilterCreatorSelectValue.scss
  packages/iris-grid/src/IrisGrid.scss
  packages/iris-grid/src/IrisGridTheme.module.scss
  packages/iris-grid/src/PendingDataBottomBar.scss
Labels: internal, breaking

#920 Copy unformatted cell for dates should copy full date string
  packages/iris-grid/src/IrisGrid.tsx
Labels: bug

#922 Add optional parameter choosing whether or not to consolidate ranges in IrisGridTableModel snapshot
  packages/iris-grid/src/IrisGridTableModelTemplate.ts
Labels: bug, grid

#775 Proxy the ws socket within vite to allow tunneling
  packages/code-studio/.env.development
  packages/code-studio/vite.config.ts
Labels: internal

#921 Fixes Grid isStuckToBottom prop doesn't work correctly on mount if rowCount doesn't increase
  packages/grid/src/Grid.tsx
  packages/grid/src/GridMetricCalculator.ts
  packages/iris-grid/src/IrisGrid.tsx
Labels: bug

#894 Update browserslist to latest defaults
  .browserslistrc
  packages/code-studio/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
Labels: internal

#930 Reduce the console height to 40/60 split in the default layout
  packages/code-studio/src/main/UserLayoutUtils.ts
Labels: enhancement

#931 Slightly reduce padding between console commands
  packages/console/src/Console.scss
  packages/console/src/common/_ConsoleVariables.scss
  packages/console/src/console-history/ConsoleHistory.scss
  packages/console/src/console-history/ConsoleHistoryItem.scss
  packages/console/src/console-history/ConsoleHistoryItem.tsx
  packages/console/src/console-history/ConsoleHistoryResultInProgress.scss
  packages/console/src/console-history/ConsoleHistoryResultInProgress.tsx
Labels: enhancement

#935 Adds copy button to version tooltip
  package-lock.json
  packages/code-studio/src/settings/SettingsMenu.scss
  packages/code-studio/src/settings/SettingsMenu.tsx
  packages/components/src/Button.tsx
  packages/components/src/CopyButton.tsx
  packages/components/src/context-actions/ContextActionUtils.ts
  packages/components/src/index.ts
  packages/console/src/command-history/CommandHistory.tsx
  packages/dashboard-core-plugins/package.json
  packages/dashboard-core-plugins/src/panels/WidgetPanel.tsx
  packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.tsx
  packages/dashboard-core-plugins/tsconfig.json
  packages/iris-grid/src/ColumnStatistics.tsx
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/IrisGridCellOverflowModal.tsx
  packages/iris-grid/src/IrisGridCopyHandler.test.tsx
  packages/iris-grid/src/IrisGridCopyHandler.tsx
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
  packages/react-hooks/package.json
  packages/react-hooks/src/index.ts
  packages/react-hooks/src/useCopyToClipboard.ts
  packages/react-hooks/tsconfig.json
  packages/utils/src/ClipboardUtils.ts
  packages/utils/src/index.ts
Labels: enhancement

#940 Fix dragging empty tables
  packages/grid/src/GridMetricCalculator.ts
Labels: bug

#941 Add Download CSV options for hidden columns, headers and formatting
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/sidebar/TableCsvExporter.scss
  packages/iris-grid/src/sidebar/TableCsvExporter.tsx
  packages/iris-grid/src/sidebar/TableSaver.tsx
Labels: enhancement

#943 Run npm audit fix
  package-lock.json
Labels: internal

#937 Allow embed-grid to open pandas dataframes
  packages/embed-grid/src/App.tsx
  packages/jsapi-utils/src/ConnectionUtils.test.ts
  packages/jsapi-utils/src/ConnectionUtils.ts
  packages/jsapi-utils/src/index.ts
Labels: enhancement

#945 Change publish tokens to deephaven-bot
  .github/workflows/publish-alpha.yml
  .github/workflows/publish-nightly.yml
  .github/workflows/publish-packages.yml
Labels: internal

#895 Add types override for memoizee
  @types/README.md
  @types/memoize-one/index.d.ts
  @types/memoizee/index.d.ts
  jest.config.base.cjs
  packages/chart/src/FigureChartModel.ts
  packages/components/src/context-actions/ContextActionUtils.ts
  packages/console/src/Console.tsx
  packages/console/src/command-history/CommandHistoryItemTooltip.tsx
  packages/console/src/csv/CsvOverlay.tsx
  packages/dashboard-core-plugins/src/controls/dropdown-filter/DropdownFilter.tsx
  packages/dashboard-core-plugins/src/controls/input-filter/InputFilter.tsx
  packages/dashboard-core-plugins/src/panels/DropdownFilterPanel.tsx
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
  packages/dashboard-core-plugins/src/panels/Panel.tsx
  packages/grid/src/Grid.tsx
  packages/grid/src/GridRenderer.ts
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/IrisGridTableModel.ts
  packages/iris-grid/src/IrisGridUtils.ts
  packages/iris-grid/src/TableViewportUpdater.tsx
  packages/iris-grid/src/sidebar/VisibilityOrderingBuilder.tsx
  packages/iris-grid/tsconfig.json
  tsconfig.json
Labels: internal

#947 Disable patch checking for codecov
  codecov.yml
Labels: internal

#933 Fix tsconfig to type check code studio
  packages/code-studio/src/main/AppControlsMenu.tsx
  packages/code-studio/src/main/AppMainContainer.tsx
  packages/code-studio/src/settings/FormattingSectionContent.tsx
  packages/code-studio/src/storage/LocalWorkspaceStorage.ts
  packages/code-studio/src/styleguide/DraggableLists.tsx
  packages/code-studio/src/styleguide/MockIrisGridTreeModel.ts
  packages/code-studio/src/styleguide/StyleGuideInit.tsx
  packages/code-studio/tsconfig.json
  packages/embed-chart/tsconfig.json
  packages/embed-grid/tsconfig.json
  tsconfig.json
Labels: internal

#926 Add buttons to linker, ability to change the comparison operator, and link combination
  package-lock.json
  packages/code-studio/src/main/AppMainContainer.scss
  packages/dashboard-core-plugins/package.json
  packages/dashboard-core-plugins/src/linker/Linker.tsx
  packages/dashboard-core-plugins/src/linker/LinkerLink.scss
  packages/dashboard-core-plugins/src/linker/LinkerLink.tsx
  packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.scss
  packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.tsx
  packages/dashboard-core-plugins/src/linker/LinkerUtils.tsx
  packages/iris-grid/src/IrisGrid.test.tsx
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/IrisGridUtils.test.ts
  packages/iris-grid/src/IrisGridUtils.ts
  packages/jsapi-utils/src/Formatter.ts
  packages/jsapi-utils/src/TableUtils.ts
Labels: enhancement

#955 Replace non-breaking spaces pasted into monaco editors
  packages/console/src/monaco/MonacoUtils.ts
Labels: bug

#957 Upgrade to TypeScript 4.9
  package-lock.json
  package.json
  packages/code-studio/src/styleguide/Charts.tsx
  packages/components/src/ValidateLabelInput.tsx
  packages/console/src/log/LogView.tsx
  packages/file-explorer/src/FileUtils.ts
  packages/golden-layout/src/config/Config.ts
  packages/iris-grid/src/AdvancedFilterCreatorSelectValueList.tsx
Labels: internal

#961 Version Bump v0.23.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/pouch-storage/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal

#948 Update Node version to latest lts/gallium
  .nvmrc
Labels: internal

#950 Integrate Playwright into GitHub Actions
  .github/workflows/e2e.yml
  .github/workflows/unit.yml
  README.md
  package-lock.json
  package.json
  playwright-report/index.html
  playwright.config.ts
  tests/console.spec.ts
  tests/figure.spec.ts
  tests/figure.spec.ts-snapshots/can-open-a-simple-figure-1-chromium-linux.png
  tests/figure.spec.ts-snapshots/can-open-a-simple-figure-1-firefox-linux.png
  tests/figure.spec.ts-snapshots/can-open-a-simple-figure-1-webkit-linux.png
  tests/notebook.spec.ts
  tests/table.spec.ts
  tests/table.spec.ts-snapshots/can-open-a-simple-table-1-chromium-linux.png
  tests/table.spec.ts-snapshots/can-open-a-simple-table-1-firefox-linux.png
  tests/table.spec.ts-snapshots/can-open-a-simple-table-1-webkit-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-advanced-filters-1-chromium-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-advanced-filters-1-firefox-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-advanced-filters-1-webkit-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-go-to-1-chromium-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-go-to-1-firefox-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-go-to-1-webkit-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-quick-filters-with-the-advanced-filters-in-above-test-applied-1-chromium-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-quick-filters-with-the-advanced-filters-in-above-test-applied-1-firefox-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-quick-filters-with-the-advanced-filters-in-above-test-applied-1-webkit-linux.png
  tests/utils.ts
Labels: internal

#959 FileExplorer tests
  packages/file-explorer/src/FileListItemEditor.test.tsx
  packages/file-explorer/src/FileListItemEditor.tsx
  packages/file-explorer/src/FileUtils.test.ts
Labels: internal

#952 Make linker dialog draggable
  package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.scss
  packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.tsx
  packages/dashboard-core-plugins/tsconfig.json
Labels: enhancement

#958 Change onclick to separate mousedown and mouseup events in Modal.tsx
  packages/components/src/modal/Modal.tsx
Labels: bug

#970 Only close documents that have been opened
  packages/console/src/notebook/ScriptEditor.tsx
Labels: bug

#967 Fix linker spamming errors, change linker dialog text, add delete key to delete selected links
  packages/dashboard-core-plugins/src/linker/Linker.tsx
  packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.tsx
Labels: enhancement

#972 Remove word "Manage" from "Manage Custom Columns"
  packages/iris-grid/src/IrisGrid.tsx
Labels: enhancement

#975 Fix closing linker using shortcut not resetting state
  packages/dashboard-core-plugins/src/linker/Linker.tsx
Labels: bug

#968 Fix weird UI when dragging a panel with linker overlay open
  packages/dashboard-core-plugins/src/linker/Linker.tsx
  packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.tsx
  packages/dashboard/src/DashboardLayout.tsx
  packages/dashboard/src/PanelEvent.ts
Labels: enhancement

#976 Add File Explorer Toolbar and small Chart Panel mount tests
  packages/dashboard-core-plugins/src/panels/ChartColumnSelectorOverlay.test.tsx
  packages/dashboard-core-plugins/src/panels/ChartFilterOverlay.test.tsx
  packages/file-explorer/src/FileExplorerToolbar.test.tsx
Labels: internal

#977 Version Bump v0.24.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/pouch-storage/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal
