Repository deephaven/web-client-ui, pull requests merged in 2022-09, with the labels that each got.

#738 DH-12503 Fix TimeSlider selection issue when swapping start/end times
  packages/components/src/CustomTimeSelect.tsx
  packages/components/src/MaskedInput.tsx
  packages/components/src/TimeInput.tsx
  packages/components/src/TimeSlider.tsx
Labels: bug

#736 DH-13043 Filter validation fixes and nulls in Advanced Filters
  packages/iris-grid/src/AdvancedFilterCreator.tsx
  packages/iris-grid/src/AdvancedFilterCreatorFilterItem.scss
  packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
  packages/iris-grid/src/IrisGrid.tsx
  packages/jsapi-utils/src/TableUtils.test.ts
  packages/jsapi-utils/src/TableUtils.ts
Labels: bug

#737 Add ValidateLabelInput component
  packages/code-studio/src/styleguide/Inputs.tsx
  packages/components/src/CustomTimeSelect.tsx
  packages/components/src/ValidateLabelInput.scss
  packages/components/src/ValidateLabelInput.test.tsx
  packages/components/src/ValidateLabelInput.tsx
  packages/components/src/index.ts
Labels: enhancement

#740 Component updates for Parameterized Query UI (cherry-pick #666)
  packages/components/src/Checkbox.tsx
  packages/components/src/Option.tsx
  packages/components/src/Select.tsx
  packages/components/src/SelectValueList.scss
  packages/components/src/SelectValueList.tsx
Labels: internal

#741 DH-9164 Fix title overlap on twin Y charts in Enterprise (cherry-pick #687)
  packages/chart/src/ChartUtils.ts
Labels: bug

#746 Blank commands not added to history
  packages/console/src/ConsoleInput.tsx
Labels: bug, good first issue

#744 Add EditableItemList component
  package-lock.json
  packages/components/package.json
  packages/components/src/EditableItemList.tsx
  packages/components/src/index.ts
Labels: enhancement

#753 Cherry-pick #744 Editable Item List
  package-lock.json
  packages/components/package.json
  packages/components/src/EditableItemList.tsx
  packages/components/src/index.ts
Labels: enhancement

#747 Update monaco version
  README.md
  __mocks__/monaco-editor-empty.js
  __mocks__/monaco-editor.js
  jest.config.base.cjs
  jest.setup.ts
  package-lock.json
  packages/console/package.json
  packages/console/src/Console.test.tsx
  packages/console/src/ConsoleInput.tsx
  packages/console/src/common/Code.tsx
  packages/console/src/log/LogView.tsx
  packages/console/src/monaco/MonacoCompletionProvider.test.tsx
  packages/console/src/monaco/MonacoCompletionProvider.tsx
  packages/console/src/monaco/MonacoUtils.test.ts
  packages/console/src/monaco/MonacoUtils.ts
  packages/console/src/monaco/lang/Language.ts
  packages/console/src/monaco/lang/db.ts
  packages/console/src/monaco/lang/groovy.ts
  packages/console/src/monaco/lang/log.ts
  packages/console/src/monaco/lang/python.ts
  packages/console/src/monaco/lang/scala.ts
  packages/console/src/notebook/Editor.tsx
  packages/dashboard-core-plugins/src/controls/markdown/MarkdownEditor.tsx
  packages/dashboard-core-plugins/src/panels/MarkdownPanel.tsx
  packages/embed-grid/package.json
  packages/iris-grid/package.json
  packages/iris-grid/src/sidebar/InputEditor.tsx
  packages/mocks/src/index.js
  packages/mocks/src/monaco-editor.js
Labels: internal

#743 Support for no console in the web UI
  __mocks__/dh-core.js
  packages/code-studio/src/main/AppInit.tsx
  packages/code-studio/src/main/AppMainContainer.test.tsx
  packages/code-studio/src/main/AppMainContainer.tsx
  packages/code-studio/src/main/NoConsolesError.ts
  packages/code-studio/src/main/SessionUtils.ts
  packages/code-studio/src/main/UserLayoutUtils.test.ts
  packages/code-studio/src/main/UserLayoutUtils.ts
  packages/code-studio/src/main/WidgetUtils.ts
  packages/code-studio/src/storage/LocalWorkspaceStorage.ts
  packages/dashboard-core-plugins/src/panels/ConsolePanel.test.tsx
  packages/dashboard-core-plugins/src/redux/actionTypes.ts
  packages/dashboard-core-plugins/src/redux/actions.ts
  packages/dashboard-core-plugins/src/redux/reducers/connection.ts
  packages/dashboard-core-plugins/src/redux/selectors.ts
  packages/embed-chart/src/App.tsx
  packages/embed-grid/src/App.tsx
  packages/jsapi-shim/src/dh.types.ts
  packages/redux/src/store.ts
Labels: enhancement

#760 Version Bump v0.17.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal

#757 Switch column header group text to dark if background is light
  package-lock.json
  packages/grid/package.json
  packages/grid/src/GridRenderer.ts
  packages/grid/src/GridTheme.ts
  packages/grid/tsconfig.json
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/IrisGridTheme.module.scss
  packages/iris-grid/src/IrisGridTheme.ts
Labels: enhancement

#764 Memoize column header isDark to fix performance issue
  packages/grid/src/GridRenderer.ts
  packages/utils/src/ColorUtils.ts
Labels: bug

#767 Cherry pick: DH-13043 Filter validation fixes and nulls in Advanced Filters
  packages/iris-grid/src/AdvancedFilterCreator.jsx
  packages/iris-grid/src/AdvancedFilterCreatorFilterItem.scss
  packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
  packages/jsapi-utils/src/TableUtils.test.js
  packages/jsapi-utils/src/TableUtils.ts
Labels: bug

#756 Date/DateTime inputs
  packages/code-studio/src/components/DateInput.jsx
  packages/code-studio/src/styleguide/Inputs.tsx
  packages/components/src/DateInput.tsx
  packages/components/src/DateInputUtils.ts
  packages/components/src/DateTimeInput.test.tsx
  packages/components/src/DateTimeInput.tsx
  packages/components/src/MaskedInput.test.tsx
  packages/components/src/MaskedInput.tsx
  packages/components/src/TimeInput.test.tsx
  packages/components/src/index.ts
Labels: enhancement

#769 Cherry-pick Date/DateTime inputs (#756)
  packages/code-studio/src/styleguide/Inputs.tsx
  packages/components/src/DateInput.tsx
  packages/components/src/DateInputUtils.ts
  packages/components/src/DateTimeInput.test.tsx
  packages/components/src/DateTimeInput.tsx
  packages/components/src/MaskedInput.test.tsx
  packages/components/src/MaskedInput.tsx
  packages/components/src/TimeInput.test.tsx
  packages/components/src/index.ts
Labels: enhancement

#771 Cherry-pick Table Input (#762)
  __mocks__/dh-core.js
  package-lock.json
  package.json
  packages/code-studio/tsconfig.json
  packages/components/src/SearchInput.tsx
  packages/components/src/SelectValueList.tsx
  packages/jsapi-components/.gitignore
  packages/jsapi-components/README.md
  packages/jsapi-components/jest.config.cjs
  packages/jsapi-components/package.json
  packages/jsapi-components/src/ColumnNameError.ts
  packages/jsapi-components/src/TableDisconnectError.ts
  packages/jsapi-components/src/TableInput.scss
  packages/jsapi-components/src/TableInput.test.tsx
  packages/jsapi-components/src/TableInput.tsx
  packages/jsapi-components/src/index.ts
  packages/jsapi-components/src/useTable.test.ts
  packages/jsapi-components/src/useTable.ts
  packages/jsapi-components/src/useTableColumn.ts
  packages/jsapi-components/src/useTableListener.ts
  packages/jsapi-components/tsconfig.json
  tsconfig.json
Labels: enhancement

#772 Version Bump v0.13.6
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-utils/package.json
  packages/redux/package.json
Labels: internal

#758 Add path information and breadcrumb interactivity to NewItemModal
  package-lock.json
  packages/components/src/Button.tsx
  packages/components/src/ItemListItem.tsx
  packages/dashboard-core-plugins/package.json
  packages/dashboard-core-plugins/src/__mocks__/react-virtualized-auto-sizer.ts
  packages/dashboard-core-plugins/src/panels/FileExplorerPanel.test.tsx
  packages/dashboard-core-plugins/src/panels/FileExplorerPanel.tsx
  packages/dashboard-core-plugins/src/panels/MockFileStorage.ts
  packages/dashboard-core-plugins/src/panels/MockFileStorageTable.ts
  packages/file-explorer/src/FileExplorer.tsx
  packages/file-explorer/src/FileExplorerToolbar.tsx
  packages/file-explorer/src/FileList.tsx
  packages/file-explorer/src/FileListContainer.tsx
  packages/file-explorer/src/NewItemModal.scss
  packages/file-explorer/src/NewItemModal.tsx
Labels: enhancement

#777 751 add path information
  packages/dashboard-core-plugins/src/panels/FileExplorerPanel.test.tsx
Labels: enhancement

#774 Fix tsconfig formatting
  packages/code-studio/tsconfig.json
Labels: internal

#778 Fix up imports after golden-layout changes
  packages/dashboard-core-plugins/src/controls/markdown/MarkdownStartPage.tsx
  packages/dashboard-core-plugins/src/panels/MarkdownPanel.test.tsx
  packages/dashboard-core-plugins/src/panels/MarkdownPanel.tsx
  packages/dashboard-core-plugins/src/panels/Panel.test.tsx
  packages/dashboard-core-plugins/src/panels/Panel.tsx
  packages/dashboard-core-plugins/src/panels/PanelContextMenu.test.tsx
  packages/dashboard-core-plugins/src/panels/PanelContextMenu.tsx
  packages/dashboard-core-plugins/src/panels/WidgetPanel.tsx
Labels: internal

#779 Version Bump v0.13.7
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-utils/package.json
  packages/redux/package.json
Labels: internal

#776 Run `npm audit fix` to update package dependencies
  package-lock.json
Labels: internal

#780 Version bump v0.18.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal

#781 Upgrade to bootstrap 4.6.2
  package-lock.json
  packages/components/package.json
Labels: internal

#783 Up/down arrows showing duplicate consecutive entries in console input
  packages/console/src/ConsoleInput.tsx
Labels: enhancement

#786 Unable to edit input table
  packages/grid/src/Grid.test.tsx
  packages/iris-grid/src/IrisGridProxyModel.ts
Labels: bug

#788 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#785 Downgrading monaco-editor to v0.31.1
  package-lock.json
  packages/console/package.json
  packages/console/src/monaco/MonacoUtils.ts
  packages/iris-grid/package.json
Labels: bug

#784 Fix broken advanced filter creator
  packages/iris-grid/src/AdvancedFilterCreator.jsx
  packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
  packages/iris-grid/src/AdvancedFilterCreatorSelectValueList.jsx
Labels: bug
