Repository deephaven/web-client-ui, pull requests merged in 2022-04, with the labels that each got.

#507 Version Bump v0.11.5
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
Labels: internal

#512 Add data-testid Attributes for CSV Download
  packages/components/src/RadioItem.tsx
  packages/components/src/navigation/MenuItem.tsx
  packages/components/src/navigation/Page.tsx
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/sidebar/TableCsvExporter.jsx
Labels: internal

#485 Fix sass deprecation warnings
  package-lock.json
  packages/code-studio/src/main/AppMainContainer.scss
  packages/components/package.json
  packages/components/src/SocketedButton.scss
  packages/components/src/TimeSlider.scss
  packages/embed-grid/package.json
  packages/stylelint-config/index.js
Labels: internal, web-client-ui

#505 Remove enzyme from ChartBuilder tests
  packages/iris-grid/src/sidebar/ChartBuilder.jsx
  packages/iris-grid/src/sidebar/ChartBuilder.test.jsx
Labels: bug

#519 Focus irisgrid on tab click
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
  packages/dashboard-core-plugins/src/panels/Panel.jsx
  packages/dashboard-core-plugins/src/panels/Panel.test.jsx
  packages/dashboard-core-plugins/src/panels/WidgetPanel.jsx
  packages/golden-layout/src/js/controls/Tab.js
  packages/iris-grid/src/IrisGrid.jsx
Labels: enhancement

#520 Enable the curly eslint rule
  packages/eslint-config/index.js
  packages/iris-grid/src/mousehandlers/IrisGridCellOverflowMouseHandler.ts
Labels: internal

#521 Fix 'Unknown columnType' warnings
  packages/iris-grid/src/Formatter.ts
Labels: bug, web-client-ui

#518 Add @testing-library/jest-dom, jest-canvas-mock
  jest.config.base.cjs
  jest.setup.ts
  package-lock.json
  package.json
  packages/embed-grid/package.json
  packages/embed-grid/src/setupTests.ts
  packages/iris-grid/src/sidebar/ChartBuilder.test.jsx
  tsconfig.json
Labels: internal

#522 Americanize golden-layout maximise label spelling
  packages/golden-layout/src/js/config/defaultConfig.js
Labels: internal, golden-layout

#479 DH-12233 Save rollups, aggregations, selectDistinct in filter sets
  packages/components/src/Button.tsx
  packages/dashboard-core-plugins/src/panels/FilterSetManager.tsx
  packages/dashboard-core-plugins/src/panels/FilterSetManagerPanel.jsx
  packages/dashboard-core-plugins/src/panels/FilterSetManagerPanel.test.tsx
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/IrisGridUtils.js
  packages/iris-grid/src/IrisGridUtils.test.js
Labels: enhancement, web-client-ui

#524 DH-12435 Fix exception on right-click in the empty space of the table
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.jsx
Labels: bug, web-client-ui, grid

#525 apr14 audit fix
  .nvmrc
  package-lock.json
  package.json
  packages/icons/config.yml
  packages/icons/package.json
  packages/icons/scripts/build.js
  packages/icons/svgo.config.js
Labels: internal

#517 Add grid ThemeContext for providing the theme in a context
  packages/code-studio/src/styleguide/Grids.jsx
  packages/grid/src/Grid.tsx
  packages/grid/src/ThemeContext.ts
  packages/grid/src/index.ts
Labels: enhancement

#527 Fix CSV download formatting
  packages/iris-grid/src/FormatterUtils.test.ts
  packages/iris-grid/src/FormatterUtils.ts
  packages/iris-grid/src/IrisGridTableModel.js
  packages/iris-grid/src/sidebar/TableSaver.jsx
Labels: bug, web-client-ui, grid

#529 Version Bump v0.11.6
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/stylelint-config/package.json
Labels: internal

#530 DH-12387 Unable to override query formatting via the custom format menu
  packages/iris-grid/src/IrisGridTableModel.js
  packages/iris-grid/src/sidebar/TableSaver.jsx
Labels: bug, web-client-ui, grid

#535 Fix vertical scroll bar when FileExplorer tab shown
  packages/file-explorer/src/FileExplorerToolbar.scss
Labels: bug

#538 DH-10208 Fix arrow up at top of history loading empty history commands
  packages/console/src/ConsoleInput.jsx
Labels: bug

#541 Version Bump v0.11.7
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/dashboard-core-plugins/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/iris-grid/package.json
Labels: internal
