Repository deephaven/web-client-ui, pull requests merged in 2022-03, with the labels that each got.

#457 DH-11189: add rowCount tooltip to table panel tab
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.scss
  packages/dashboard-core-plugins/src/panels/WidgetPanel.jsx
  packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.jsx
Labels: enhancement

#454 add component mount test for styleguide
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/code-studio/src/styleguide/StyleGuide.test.jsx
  packages/components/package-lock.json
  packages/embed-grid/package-lock.json
  packages/golden-layout/package-lock.json
  packages/mocks/src/monaco-editor.js
  packages/stylelint-config/package-lock.json
  packages/utils/package-lock.json
Labels: internal, debt

#465 Remove listeners before setting next model
  packages/iris-grid/src/IrisGridProxyModel.js
Labels: bug, web-client-ui

#460 Add the package directory to each packages package.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/embed-grid/package-lock.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal, web-client-ui

#464 DH-9064: Truncate file-explorer name overflow, and tooltip
  packages/file-explorer/src/FileList.scss
  packages/file-explorer/src/FileList.tsx
Labels: enhancement

#466 Fix rollup config not being able to be removed
  packages/iris-grid/src/IrisGridModel.ts
  packages/iris-grid/src/IrisGridModelUpdater.jsx
  packages/iris-grid/src/IrisGridModelUpdater.tsx
Labels: bug, web-client-ui

#468 remove last line from editor selection if cursor is in column 1
  packages/console/src/notebook/ScriptEditor.jsx
Labels: bug, notebook

#463 DH-10082 Fix unexpected time input behaviour
  packages/components/src/MaskedInput.tsx
  packages/components/src/TimeInput.test.tsx
  packages/components/src/TimeInput.tsx
Labels: bug, web-client-ui

#470 DH-12087 Allow better handling when disconnected
  packages/console/src/Console.jsx
  packages/console/src/ConsoleInput.jsx
  packages/console/src/console-history/ConsoleHistory.jsx
  packages/console/src/console-history/ConsoleHistoryItem.jsx
  packages/console/src/console-history/ConsoleHistoryResultInProgress.jsx
  packages/console/src/csv/CsvInputBar.jsx
Labels: enhancement, web-client-ui

#473 Fix some console history styling
  packages/console/src/Console.jsx
  packages/console/src/Console.scss
  packages/console/src/console-history/ConsoleHistoryResultInProgress.scss
Labels: bug, web-client-ui

#474 Update readme links to absolute paths
  packages/grid/README.md
Labels: internal, web-client-ui

#478 Use empty object for props if undefined
  packages/dashboard/src/layout/LayoutUtils.js
Labels: bug, web-client-ui

#482 Version Bump v0.11.2
  lerna.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/embed-grid/package-lock.json
  packages/embed-grid/package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package-lock.json
  packages/mocks/package.json
  packages/prettier-config/package-lock.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/stylelint-config/package-lock.json
  packages/stylelint-config/package.json
  packages/tsconfig/package-lock.json
  packages/tsconfig/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal, web-client-ui

#469 Upgrade to node v16/npm v8
  .github/workflows/create-release.yml
  .github/workflows/node.js.yml
  .github/workflows/publish-alpha.yml
  .github/workflows/publish-nightly.yml
  .github/workflows/publish-packages.yml
  .nvmrc
  README.md
  examples/component-template/package.json
  package-lock.json
  package.json
  packages/babel-preset/package-lock.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/code-studio/src/main/LayoutStorage.ts
  packages/code-studio/src/main/UserLayoutUtils.test.ts
  packages/code-studio/src/main/UserLayoutUtils.ts
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard-core-plugins/src/index.ts
  packages/dashboard-core-plugins/src/panels/index.ts
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/embed-grid/package-lock.json
  packages/embed-grid/package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package-lock.json
  packages/prettier-config/package-lock.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/stylelint-config/package-lock.json
  packages/tsconfig/package-lock.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal, breaking

#453 DH-10111: Display cell overflow
  package-lock.json
  packages/console/src/monaco/MonacoUtils.js
  packages/grid/src/Grid.scss
  packages/grid/src/GridMouseHandler.ts
  packages/grid/src/GridRenderer.ts
  packages/grid/src/GridUtils.ts
  packages/iris-grid/package.json
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/IrisGrid.test.jsx
  packages/iris-grid/src/IrisGridCellOverflowModal.scss
  packages/iris-grid/src/IrisGridCellOverflowModal.tsx
  packages/iris-grid/src/IrisGridRenderer.js
  packages/iris-grid/src/IrisGridTheme.module.scss
  packages/iris-grid/src/IrisGridTheme.ts
  packages/iris-grid/src/TableUtils.ts
  packages/iris-grid/src/filters/FilterOperator.ts
  packages/iris-grid/src/filters/FilterType.ts
  packages/iris-grid/src/mousehandlers/IrisGridCellOverflowMouseHandler.ts
  packages/iris-grid/src/mousehandlers/index.ts
  packages/iris-grid/tsconfig.json
  packages/storage/package.json
  packages/storage/src/StorageUtils.ts
  packages/storage/src/filters/FilterOperator.ts
  packages/storage/src/filters/FilterType.ts
  packages/storage/src/filters/index.ts
  packages/storage/src/index.ts
  packages/storage/tsconfig.json
Labels: enhancement

#486 rm enzyme: FormattingSectionContent refactor
  packages/code-studio/src/settings/FormattingSectionContent.jsx
  packages/code-studio/src/settings/FormattingSectionContent.test.jsx
Labels: internal, debt

#490 Switch to NPM 8 Workspaces
  .gitignore
  package-lock.json
  package.json
  packages/babel-preset/package-lock.json
  packages/chart/package-lock.json
  packages/code-studio/package-lock.json
  packages/code-studio/src/styleguide/StyleGuide.test.jsx
  packages/components/package-lock.json
  packages/console/package-lock.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard/package-lock.json
  packages/embed-grid/package-lock.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/golden-layout/package-lock.json
  packages/grid/package-lock.json
  packages/icons/package-lock.json
  packages/iris-grid/package-lock.json
  packages/jsapi-shim/package-lock.json
  packages/log/package-lock.json
  packages/mocks/package-lock.json
  packages/prettier-config/package-lock.json
  packages/react-hooks/package-lock.json
  packages/redux/package-lock.json
  packages/storage/package-lock.json
  packages/stylelint-config/package-lock.json
  packages/tsconfig/package-lock.json
  packages/utils/package-lock.json
Labels: enhancement

#489 Disable formatting for array columns
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionEditor.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormatEditor.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingMenu.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.ts
Labels: bug, web-client-ui, grid

#492 rm enzyme: refactor ConsoleStatusBar to use RTL
  packages/console/src/ConsoleStatusBar.test.jsx
Labels: internal, debt

#493 Re-enable Codecov reporting
  .github/workflows/node.js.yml
  .stylelintignore
  jest.config.cjs
  jest.config.lint.cjs
  jest.config.unit.cjs
  package.json
Labels: internal

#487 DH-12166: Allow truncating number columns with pound symbol
  packages/code-studio/src/main/AppInit.jsx
  packages/code-studio/src/settings/FormattingSectionContent.jsx
  packages/grid/src/GridModel.ts
  packages/grid/src/GridRenderer.ts
  packages/iris-grid/src/Formatter.ts
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/IrisGrid.test.jsx
  packages/iris-grid/src/IrisGridProxyModel.js
  packages/iris-grid/src/IrisGridRenderer.js
  packages/iris-grid/src/IrisGridTableModel.js
  packages/redux/src/selectors.ts
  packages/redux/src/store.ts
Labels: enhancement

#495 Always populate the calculated item size maps
  packages/grid/src/GridMetricCalculator.ts
  packages/iris-grid/src/IrisGridMetricCalculator.ts
Labels: bug

#501 Update package.json with file: links
  examples/component-template/package.json
  package-lock.json
  package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/log/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/utils/package.json
Labels: internal

#502 web v0.11.4
  lerna.json
  package-lock.json
  package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/log/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/utils/package.json
Labels: internal

#503 npm audit fix
  package-lock.json
Labels: internal
