Repository deephaven/web-client-ui, pull requests merged in 2022-01, with the labels that each got.

#367 Catch error if unable to fetch layout list
  packages/code-studio/src/main/UserLayoutUtils.ts
Labels: bug, web-client-ui

#362 Add support for updating the default decimal/integer formats
  packages/chart/src/Chart.jsx
  packages/code-studio/src/settings/FormattingSectionContent.jsx
  packages/code-studio/src/settings/FormattingSectionContent.test.jsx
  packages/iris-grid/src/Formatter.js
  packages/iris-grid/src/IrisGrid.jsx
  packages/iris-grid/src/formatters/DateTimeColumnFormatter.ts
  packages/iris-grid/src/formatters/DecimalColumnFormatter.js
  packages/iris-grid/src/formatters/DecimalColumnFormatter.ts
  packages/iris-grid/src/formatters/IntegerColumnFormatter.js
  packages/iris-grid/src/formatters/IntegerColumnFormatter.ts
  packages/iris-grid/src/formatters/index.ts
  packages/redux/src/selectors.ts
  packages/redux/src/store.ts
Labels: enhancement, breaking

#356 Make redefined shortcuts work in monaco
  jest.config.base.cjs
  packages/code-studio/src/settings/ShortcutsSectionContent.tsx
  packages/components/package.json
  packages/components/src/shortcuts/Shortcut.ts
  packages/components/src/shortcuts/ShortcutRegistry.test.ts
  packages/components/src/shortcuts/ShortcutRegistry.ts
  packages/console/src/ConsoleShortcuts.ts
  packages/console/src/monaco/MonacoUtils.js
  packages/console/src/monaco/MonacoUtils.test.ts
  packages/console/src/notebook/ScriptEditor.jsx
  packages/dashboard-core-plugins/src/panels/NotebookPanel.jsx
  packages/dashboard-core-plugins/src/panels/Shortcuts.ts
  packages/dashboard-core-plugins/src/panels/index.js
  packages/eslint-config/index.js
  packages/utils/src/EventTargetShimUtils.ts
  packages/utils/src/index.ts
Labels: bug

#373 Settings Reset to Defaults
  packages/code-studio/src/main/AppInit.jsx
  packages/code-studio/src/settings/FormattingSectionContent.jsx
  packages/code-studio/src/settings/FormattingSectionContent.scss
  packages/code-studio/src/settings/FormattingSectionContent.test.jsx
  packages/code-studio/src/storage/LocalWorkspaceStorage.ts
  packages/code-studio/src/storage/WorkspaceStorage.ts
Labels: enhancement, web-client-ui

#372 Iris-grid TypeScript Part 1
  packages/dashboard-core-plugins/src/linker/Linker.tsx
  packages/grid/src/GridMetricCalculator.ts
  packages/grid/src/GridTheme.ts
  packages/grid/src/index.ts
  packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
  packages/iris-grid/src/DateUtils.test.ts
  packages/iris-grid/src/DateUtils.ts
  packages/iris-grid/src/Formatter.js
  packages/iris-grid/src/Formatter.test.ts
  packages/iris-grid/src/Formatter.ts
  packages/iris-grid/src/FormatterUtils.js
  packages/iris-grid/src/FormatterUtils.ts
  packages/iris-grid/src/IrisGridMetricCalculator.ts
  packages/iris-grid/src/IrisGridTheme.ts
  packages/iris-grid/src/TableUtils.ts
  packages/iris-grid/src/declaration.d.ts
  packages/iris-grid/src/filters/FilterOperator.js
  packages/iris-grid/src/filters/FilterOperator.ts
  packages/iris-grid/src/filters/FilterType.js
  packages/iris-grid/src/filters/FilterType.ts
  packages/iris-grid/src/filters/index.js
  packages/iris-grid/src/filters/index.ts
  packages/iris-grid/src/format-context-menus/CustomFormatAction.tsx
  packages/iris-grid/src/format-context-menus/DateTimeFormatContextMenu.ts
  packages/iris-grid/src/format-context-menus/DecimalFormatContextMenu.ts
  packages/iris-grid/src/format-context-menus/FormatContextMenuUtils.jsx
  packages/iris-grid/src/format-context-menus/FormatContextMenuUtils.tsx
  packages/iris-grid/src/format-context-menus/IntegerFormatContextMenu.ts
  packages/iris-grid/src/format-context-menus/index.ts
  packages/iris-grid/src/formatters/BooleanColumnFormatter.ts
  packages/iris-grid/src/formatters/CharColumnFormatter.ts
  packages/iris-grid/src/formatters/DateTimeColumnFormatter.test.ts
  packages/iris-grid/src/formatters/DateTimeColumnFormatter.ts
  packages/iris-grid/src/formatters/DecimalColumnFormatter.ts
  packages/iris-grid/src/formatters/DefaultColumnFormatter.ts
  packages/iris-grid/src/formatters/IntegerColumnFormatter.ts
  packages/iris-grid/src/formatters/NumberColumnFormatter.test.ts
  packages/iris-grid/src/formatters/index.ts
  packages/iris-grid/src/index.js
  packages/iris-grid/src/sidebar/aggregations/AggregationEdit.tsx
  packages/iris-grid/src/sidebar/aggregations/AggregationUtils.ts
  packages/jsapi-shim/src/dh.types.ts
  packages/jsapi-shim/src/index.ts
  packages/redux/package.json
  packages/redux/src/store.ts
  packages/redux/tsconfig.json
Labels: enhancement

#384 Version Bump v0.9.0
  lerna.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/mocks/package-lock.json
  packages/mocks/package.json
  packages/prettier-config/package-lock.json
  packages/prettier-config/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/stylelint-config/package-lock.json
  packages/stylelint-config/package.json
  packages/tsconfig/package-lock.json
  packages/tsconfig/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal, web-client-ui

#386 Maintain temporary edits to console history items until execution
  packages/console/src/ConsoleInput.jsx
Labels: enhancement, web-client-ui

#380 Add vscode workspace shared settings
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  packages/code-studio/README.md
Labels: internal, web-client-ui

#369 Deep linking notebooks
  packages/code-studio/.env
  packages/code-studio/.env.development
  packages/code-studio/package.json
  packages/code-studio/src/DownloadServiceWorkerUtils.js
  packages/code-studio/src/main/AppMainContainer.jsx
  packages/code-studio/src/main/AppRouter.jsx
  packages/dashboard/package.json
  packages/dashboard/src/Dashboard.tsx
  packages/dashboard/src/DashboardLayout.tsx
  packages/dashboard/src/layout/LayoutUtils.js
  tsconfig.json
Labels: enhancement, web-client-ui

#379 Upgrade to TypeScript 4.5
  examples/component-template/package.json
  package-lock.json
  package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/components/src/context-actions/ContextActionUtils.ts
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/file-explorer/package.json
  packages/grid/package.json
  packages/grid/src/Grid.tsx
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/log/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/utils/package.json
  packages/utils/src/EventTargetShimUtils.ts
  packages/utils/src/PromiseUtils.ts
Labels: internal, web-client-ui

#389 Fix babel public class fields plugin
  packages/babel-preset/index.js
  packages/utils/src/EventTargetShimUtils.ts
Labels: bug

#387 hide search bar toggle if serverConfig showSearch is false
  packages/iris-grid/src/IrisGrid.jsx
Labels: enhancement

#391 Dependabot fixes - follow-redirect issue
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
Labels: internal, web-client-ui

#395 Disable Codecov
  .github/workflows/node.js.yml
Labels: internal, web-client-ui

#396 Allow theme to be passed in as a prop to GridPlugin and IrisGridPanel
  packages/dashboard-core-plugins/src/GridPlugin.tsx
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
  packages/iris-grid/src/index.ts
Labels: enhancement, web-client-ui

#401 Remove Chart.modules.scss
  packages/chart/src/Chart.jsx
  packages/chart/src/Chart.module.scss
  packages/chart/src/Chart.scss
Labels: bug, web-client-ui

#388 Run type checks from root
  examples/component-template/README.md
  examples/component-template/package.json
  examples/component-template/tsconfig.json
  package.json
  packages/chart/package.json
  packages/chart/src/ChartModelFactory.js
  packages/code-studio/package.json
  packages/code-studio/src/main/WidgetUtils.ts
  packages/code-studio/tsconfig.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/file-explorer/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/grid/src/index.ts
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/log/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/redux/src/store.ts
  packages/storage/package.json
  packages/utils/package.json
  tsconfig.build.json
  tsconfig.json
Labels: enhancement

#377 Markdown Notebooks
  packages/chart/package-lock.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/console/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard-core-plugins/src/panels/MarkdownNotebook.jsx
  packages/dashboard-core-plugins/src/panels/MarkdownNotebook.scss
  packages/dashboard-core-plugins/src/panels/NotebookPanel.jsx
  packages/dashboard/package-lock.json
  packages/dashboard/src/layout/LayoutUtils.js
  packages/file-explorer/package-lock.json
  packages/grid/package-lock.json
  packages/iris-grid/package-lock.json
  packages/jsapi-shim/package-lock.json
  packages/log/package-lock.json
  packages/react-hooks/package-lock.json
  packages/redux/package-lock.json
  packages/storage/package-lock.json
  packages/utils/package-lock.json
Labels: enhancement, web-client-ui

#402 Fix the pandas plugin to actually open tables
  packages/dashboard-core-plugins/src/PandasPlugin.tsx
Labels: bug

#397 Create @deephaven/embed-grid
  CONTRIBUTING.md
  package.json
  packages/code-studio/CONTRIBUTING.md
  packages/code-studio/package-lock.json
  packages/components/package-lock.json
  packages/embed-grid/.env
  packages/embed-grid/.env.development
  packages/embed-grid/.env.test
  packages/embed-grid/.gitignore
  packages/embed-grid/.prettierignore
  packages/embed-grid/README.md
  packages/embed-grid/jest.config.cjs
  packages/embed-grid/licenses.txt
  packages/embed-grid/package-lock.json
  packages/embed-grid/package.json
  packages/embed-grid/public/favicon-cc-app-dev.svg
  packages/embed-grid/public/favicon-cc-app.svg
  packages/embed-grid/public/favicon.ico
  packages/embed-grid/public/index.html
  packages/embed-grid/public/logo
  packages/embed-grid/public/manifest.json
  packages/embed-grid/src/App.scss
  packages/embed-grid/src/App.tsx
  packages/embed-grid/src/index.scss
  packages/embed-grid/src/index.tsx
  packages/embed-grid/src/logo.svg
  packages/embed-grid/src/react-app-env.d.ts
  packages/embed-grid/src/setupTests.ts
  packages/embed-grid/tsconfig.json
  packages/iris-grid/src/IrisGrid.jsx
Labels: enhancement

#403 web v0.9.1
  README.md
  lerna.json
  packages/babel-preset/package-lock.json
  packages/babel-preset/package.json
  packages/chart/package-lock.json
  packages/chart/package.json
  packages/code-studio/package-lock.json
  packages/code-studio/package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/console/package-lock.json
  packages/console/package.json
  packages/dashboard-core-plugins/package-lock.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package-lock.json
  packages/dashboard/package.json
  packages/embed-grid/package-lock.json
  packages/embed-grid/package.json
  packages/file-explorer/package-lock.json
  packages/file-explorer/package.json
  packages/golden-layout/package-lock.json
  packages/golden-layout/package.json
  packages/grid/package-lock.json
  packages/grid/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/iris-grid/package-lock.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package-lock.json
  packages/jsapi-shim/package.json
  packages/log/package-lock.json
  packages/log/package.json
  packages/react-hooks/package-lock.json
  packages/react-hooks/package.json
  packages/redux/package-lock.json
  packages/redux/package.json
  packages/storage/package-lock.json
  packages/storage/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: internal, web-client-ui

#407 Fix for resizing columns
  packages/grid/src/GridMetricCalculator.ts
Labels: bug
