Repository deephaven/web-client-ui, pull requests merged in 2022-07, with the labels that each got.

#635 Fix issue with not showing all data and not showing scroll bar
  packages/grid/src/Grid.tsx
Labels: bug

#636 Fix Pandas table not re-hydrating properly
  packages/code-studio/src/main/AppMainContainer.jsx
  packages/code-studio/src/main/WidgetUtils.ts
Labels: bug

#545 Treemaps
  package-lock.json
  packages/chart/package.json
  packages/chart/src/ChartUtils.js
  packages/chart/src/ChartUtils.test.js
  packages/chart/src/FigureChartModel.js
  packages/chart/src/plotly/Plotly.js
  packages/jsapi-shim/src/dh.types.ts
Labels: enhancement

#634 DH-12796: fixed redux workspace types redeclared in code-studio error
  packages/code-studio/src/storage/LocalWorkspaceStorage.ts
  packages/code-studio/src/storage/WorkspaceStorage.ts
  packages/code-studio/src/styleguide/StyleGuideInit.tsx
  packages/iris-grid/src/IrisGrid.test.tsx
  packages/redux/src/selectors.ts
  packages/redux/src/store.ts
Labels: bug, breaking

#649 Fix filter set capture failing on timestamp column advanced filters, DH-12754
  packages/dashboard-core-plugins/src/panels/FilterSetManagerPanel.jsx
Labels: bug

#638 Added Goto row feature in Iris Grid
  packages/grid/src/Grid.tsx
  packages/iris-grid/src/GotoRow.scss
  packages/iris-grid/src/GotoRow.tsx
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/IrisGridShortcuts.ts
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
  packages/iris-grid/src/sidebar/OptionType.ts
Labels: enhancement

#655 Version Bump v0.15.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal

#654 Fix default layout init
  packages/code-studio/src/main/AppInit.jsx
  packages/code-studio/src/main/UserLayoutUtils.test.ts
  packages/code-studio/src/main/UserLayoutUtils.ts
  packages/code-studio/src/storage/LayoutStorage.ts
  packages/code-studio/src/storage/LocalWorkspaceStorage.ts
  packages/code-studio/src/storage/WebdavLayoutStorage.ts
  packages/code-studio/src/styleguide/StyleGuideInit.tsx
  packages/redux/src/store.ts
Labels: bug

#645 Convert Log package to typescript
  packages/log/src/DefaultLogger.ts
  packages/log/src/Log.ts
  packages/log/src/Logger.js
  packages/log/src/Logger.ts
  packages/log/src/LoggerLevel.ts
Labels: enhancement

#668 Add dist-tag to Publish Packages workflow
  .github/workflows/publish-packages.yml
Labels: internal

#664 Fix broken ctrl+e to clear filters shortcut
  packages/code-studio/src/main/AppMainContainer.jsx
  packages/grid/src/key-handlers/SelectionKeyHandler.ts
Labels: bug

#615 Scrollbar Selection Ticks
  packages/grid/src/GridRenderer.ts
  packages/grid/src/GridTheme.ts
  packages/grid/src/GridUtils.test.ts
  packages/grid/src/GridUtils.ts
  packages/iris-grid/src/IrisGridTheme.module.scss
  packages/iris-grid/src/IrisGridTheme.ts
Labels: enhancement

#657 Go to row UX cleanup
  packages/grid/src/Grid.tsx
  packages/iris-grid/src/GotoRow.scss
  packages/iris-grid/src/GotoRow.tsx
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
Labels: enhancement

#673 Allow copying the widget name from tab context menu
  packages/dashboard-core-plugins/src/panels/Panel.jsx
  packages/dashboard-core-plugins/src/panels/WidgetPanel.jsx
  packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.jsx
  packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.scss
Labels: enhancement

#674 Version Bump v0.15.1
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/grid/package.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/redux/package.json
  packages/storage/package.json
Labels: internal

#682 Fix model column [0] missing collapsed filter indicator
  packages/iris-grid/src/IrisGridRenderer.ts
Labels: bug

#685 fixed unable to open csv
  packages/console/src/Console.tsx
Labels: bug

#684 fixed copy cell unformatted not working in Long cells
  packages/components/src/context-actions/ContextActionUtils.ts
Labels: bug

#686 Fix broken conditional formatting sidebar
  packages/iris-grid/src/IrisGrid.tsx
Labels: bug

#659 dashboard typescript conversion
  package-lock.json
  packages/dashboard-core-plugins/src/ChartPlugin.tsx
  packages/dashboard-core-plugins/src/linker/Linker.tsx
  packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.tsx
  packages/dashboard-core-plugins/src/linker/LinkerUtils.tsx
  packages/dashboard-core-plugins/src/redux/actions.js
  packages/dashboard/package.json
  packages/dashboard/src/Dashboard.tsx
  packages/dashboard/src/DashboardLayout.tsx
  packages/dashboard/src/PanelErrorBoundary.tsx
  packages/dashboard/src/PanelEvent.ts
  packages/dashboard/src/PanelManager.ts
  packages/dashboard/src/PanelPlaceholder.jsx
  packages/dashboard/src/PanelPlaceholder.tsx
  packages/dashboard/src/__mocks__/@deephaven/golden-layout.ts
  packages/dashboard/src/declaration.d.ts
  packages/dashboard/src/layout/GLPropTypes.ts
  packages/dashboard/src/layout/GoldenLayoutThemeExport.ts
  packages/dashboard/src/layout/LayoutUtils.test.ts
  packages/dashboard/src/layout/LayoutUtils.ts
  packages/dashboard/src/layout/ReactDOM.ts
  packages/dashboard/src/layout/golden-layout.ts
  packages/dashboard/src/layout/jquery.ts
  packages/dashboard/src/redux/actionTypes.ts
  packages/dashboard/src/redux/actions.js
  packages/dashboard/src/redux/actions.ts
  packages/dashboard/src/redux/reducers/dashboardData.ts
  packages/dashboard/src/redux/reducers/index.ts
  packages/dashboard/src/redux/selectors.js
  packages/dashboard/src/redux/selectors.ts
  packages/dashboard/tsconfig.json
  packages/golden-layout/index.d.ts
  packages/redux/src/store.ts
Labels: enhancement

#687 DH-9164 Fix title overlap on twin Y charts in Enterprise
  packages/chart/src/ChartUtils.js
Labels: bug, web-client-ui

#688 Improve copy button alignment in widget panel tooltip
  packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.jsx
Labels: bug

#680 Fixed missing boolean menu
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
Labels: bug

#679 Clean up treemap in web UI
  packages/chart/src/ChartUtils.js
  packages/chart/src/FigureChartModel.js
Labels: bug

#690 Fix up dashboard layout utils TS conversion changes
  package-lock.json
  packages/dashboard/src/layout/LayoutUtils.ts
Labels: bug

#692 Version Bump v0.13.5
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/iris-grid/package.json
Labels: internal

#683 Add "Copy" button to cell overflow preview modal
  packages/iris-grid/src/IrisGridCellOverflowModal.tsx
Labels: enhancement

#681 Fix broken advanced filter creator
  packages/iris-grid/src/AdvancedFilterCreator.tsx
  packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
  packages/iris-grid/src/AdvancedFilterCreatorSelectValue.tsx
  packages/iris-grid/src/AdvancedFilterCreatorSelectValueList.tsx
  packages/iris-grid/src/IrisGrid.tsx
  packages/jsapi-utils/src/TableUtils.ts
Labels: bug

#642 DH-12182: Column Grouping
  packages/code-studio/src/styleguide/MockIrisGridTreeModel.ts
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
  packages/grid/src/ColumnHeaderGroup.ts
  packages/grid/src/Grid.tsx
  packages/grid/src/GridAxisRange.ts
  packages/grid/src/GridMetricCalculator.ts
  packages/grid/src/GridMetrics.ts
  packages/grid/src/GridModel.ts
  packages/grid/src/GridRenderer.ts
  packages/grid/src/GridUtils.test.ts
  packages/grid/src/GridUtils.ts
  packages/grid/src/MockGridModel.ts
  packages/grid/src/index.ts
  packages/grid/src/mouse-handlers/GridColumnMoveMouseHandler.ts
  packages/grid/src/mouse-handlers/GridColumnSeparatorMouseHandler.ts
  packages/grid/src/mouse-handlers/GridRowSeparatorMouseHandler.ts
  packages/grid/src/mouse-handlers/GridSeparatorMouseHandler.ts
  packages/grid/src/mouse-handlers/index.js
  packages/iris-grid/src/ColumnHeaderGroup.ts
  packages/iris-grid/src/IrisGrid.scss
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/IrisGridMetricCalculator.ts
  packages/iris-grid/src/IrisGridProxyModel.ts
  packages/iris-grid/src/IrisGridRenderer.ts
  packages/iris-grid/src/IrisGridTableModel.ts
  packages/iris-grid/src/IrisGridTableModelTemplate.ts
  packages/iris-grid/src/IrisGridTheme.module.scss
  packages/iris-grid/src/IrisGridTheme.ts
  packages/iris-grid/src/IrisGridUtils.test.ts
  packages/iris-grid/src/IrisGridUtils.ts
  packages/iris-grid/src/mousehandlers/IrisGridColumnTooltipMouseHandler.ts
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
  packages/iris-grid/src/mousehandlers/IrisGridFilterMouseHandler.ts
  packages/iris-grid/src/mousehandlers/IrisGridSortMouseHandler.ts
  packages/jsapi-shim/src/dh.types.ts
  packages/tsconfig/tsconfig.json
Labels: enhancement

#696 Version Bump v0.15.2
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/tsconfig/package.json
Labels: internal
