Repository deephaven/web-client-ui, pull requests merged in 2022-08, with the labels that each got.

#697 Fix layout utils react config
  packages/dashboard/src/layout/LayoutUtils.ts
  packages/iris-grid/src/IrisGridProxyModel.ts
Labels: bug

#699 Version Bump v0.15.3
  lerna.json
  package-lock.json
  packages/code-studio/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/iris-grid/package.json
Labels: internal

#704 Fixed Linker throwing an error when clicking empty space with the linker active
  packages/iris-grid/src/mousehandlers/IrisGridColumnSelectMouseHandler.ts
Labels: bug

#706 Version Bump v0.15.4
  lerna.json
  package-lock.json
  packages/code-studio/package.json
  packages/dashboard-core-plugins/package.json
  packages/embed-grid/package.json
  packages/iris-grid/package.json
Labels: internal

#702 Remove environment variables from packages
  README.md
  jest.setup.ts
  packages/code-studio/.env
  packages/code-studio/.env.development
  packages/code-studio/README.md
  packages/code-studio/src/log/LogInit.ts
  packages/code-studio/src/main/AppMainContainer.jsx
  packages/console/src/common/ConsoleConstants.ts
  packages/console/src/common/ConsoleUtils.ts
  packages/dashboard-core-plugins/src/ConsolePlugin.tsx
  packages/dashboard-core-plugins/src/panels/NotebookPanel.jsx
  packages/embed-grid/.env
  packages/embed-grid/.env.development
  packages/embed-grid/src/App.tsx
  packages/log/src/DefaultLogger.ts
  packages/log/src/Logger.ts
Labels: enhancement

#709 Provide the `outsidetextfont` for treemap charts
  packages/chart/src/ChartUtils.js
Labels: bug, web-client-ui

#714 Only collect code coverage in CI
  README.md
  jest.config.cjs
Labels: enhancement

#720 Check both componentName and component.type for react-component
  packages/dashboard/src/layout/LayoutUtils.ts
Labels: bug

#724 Version Bump v0.15.5
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/redux/package.json
  packages/storage/package.json
Labels: internal

#705 Don't check outside of min/max column bounds for groupings
  packages/grid/src/GridRenderer.ts
Labels: bug

#728 Fix broken contextmenu handler again.
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
  packages/iris-grid/src/format-context-menus/DateTimeFormatContextMenu.ts
  packages/iris-grid/src/format-context-menus/FormatContextMenuUtils.tsx
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
  packages/jsapi-utils/src/formatters/DateTimeColumnFormatter.ts
  packages/jsapi-utils/src/formatters/DecimalColumnFormatter.ts
  packages/jsapi-utils/src/formatters/IntegerColumnFormatter.ts
  packages/jsapi-utils/src/formatters/TableColumnFormatter.ts
Labels: bug

#729 Fix missing props in pandas panel by using correct import
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
  packages/dashboard-core-plugins/src/panels/PandasPanel.tsx
Labels: bug

#718 Heap size UI
  package-lock.json
  packages/chart/src/index.ts
  packages/components/src/popper/Tooltip.tsx
  packages/console/package.json
  packages/console/src/HeapUsage.scss
  packages/console/src/HeapUsage.tsx
  packages/console/src/index.ts
  packages/console/tsconfig.json
  packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx
  packages/jsapi-shim/src/dh.types.ts
  packages/redux/src/actions.ts
  packages/redux/tsconfig.json
Labels: enhancement

#731 Version Bump v0.15.6
  lerna.json
  package-lock.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/grid/package.json
  packages/iris-grid/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/redux/package.json
  packages/utils/package.json
Labels: internal

#707 Create @deephaven/embed-chart
  package-lock.json
  package.json
  packages/embed-chart/.env
  packages/embed-chart/.env.development
  packages/embed-chart/.env.test
  packages/embed-chart/.gitignore
  packages/embed-chart/.prettierignore
  packages/embed-chart/README.md
  packages/embed-chart/jest.config.cjs
  packages/embed-chart/licenses.txt
  packages/embed-chart/package.json
  packages/embed-chart/public/favicon-cc-app-dev.svg
  packages/embed-chart/public/favicon-cc-app.svg
  packages/embed-chart/public/index.html
  packages/embed-chart/public/manifest.json
  packages/embed-chart/src/App.scss
  packages/embed-chart/src/App.tsx
  packages/embed-chart/src/index.scss
  packages/embed-chart/src/index.tsx
  packages/embed-chart/src/logo.svg
  packages/embed-chart/src/react-app-env.d.ts
  packages/embed-chart/tsconfig.json
  packages/embed-grid/src/App.tsx
Labels: enhancement, web-client-ui
