Repository deephaven/web-client-ui, pull requests merged in 2023-01, with the labels that each got.

#954 Add tests for DropdownFilter
  packages/components/src/SocketedButton.tsx
  packages/dashboard-core-plugins/src/controls/dropdown-filter/DropdownFilter.test.tsx
  packages/dashboard-core-plugins/src/controls/dropdown-filter/DropdownFilter.tsx
  packages/dashboard-core-plugins/src/panels/DropdownFilterPanel.test.tsx
  packages/dashboard-core-plugins/src/panels/DropdownFilterPanel.tsx
Labels: internal

#978 DH-13988 Fix issue with old buttons not getting disabled in console history
  packages/console/src/Console.tsx
  tests/console.spec.ts
  tests/table.spec.ts
  tests/utils.ts
Labels: bug

#984 Use showLegend specified by JS API
  __mocks__/dh-core.js
  packages/chart/src/ChartTestUtils.ts
  packages/chart/src/ChartUtils.ts
  packages/chart/src/FigureChartModel.test.ts
  packages/chart/src/FigureChartModel.ts
  packages/jsapi-shim/src/dh.types.ts
Labels: enhancement

#992 Change tooltip default placement to bottom instead of auto
  packages/components/scss/BaseStyleSheet.scss
  packages/components/src/popper/Popper.tsx
  packages/components/src/popper/Tooltip.tsx
  packages/console/src/ConsoleMenu.tsx
  packages/dashboard-core-plugins/src/panels/RenameDialog.tsx
  packages/file-explorer/src/FileList.tsx
Labels: internal

#993 Fix scrollbars drawing without handles when grid is the perfect size
  packages/grid/src/GridMetricCalculator.ts
Labels: bug

#996 Version Bump v0.25.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/pouch-storage/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal

#1000 Fix default button focusing on BasicModal re-render
  packages/components/src/BasicModal.test.tsx
  packages/components/src/BasicModal.tsx
Labels: bug

#997 Add all and visible maps for row/column size/position
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
  packages/grid/src/Grid.tsx
  packages/grid/src/GridMetricCalculator.ts
  packages/grid/src/GridMetrics.ts
  packages/grid/src/GridRenderer.ts
  packages/grid/src/GridUtils.ts
  packages/grid/src/mouse-handlers/GridColumnMoveMouseHandler.ts
  packages/grid/src/mouse-handlers/GridHorizontalScrollBarMouseHandler.ts
  packages/grid/src/mouse-handlers/GridRowMoveMouseHandler.ts
  packages/grid/src/mouse-handlers/GridRowTreeMouseHandler.ts
  packages/grid/src/mouse-handlers/GridVerticalScrollBarMouseHandler.ts
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/IrisGridRenderer.ts
Labels: enhancement

#998 Fix cannot scroll left after marking columns as hidden
  packages/grid/src/Grid.tsx
  packages/grid/src/GridRenderer.ts
Labels: bug

#988 Hierarchical table support
  packages/console/src/common/ConsoleUtils.ts
  packages/console/src/common/ObjectIcon.tsx
  packages/dashboard-core-plugins/src/GridPlugin.tsx
  packages/embed-grid/src/App.tsx
  packages/jsapi-shim/src/dh.types.ts
Labels: enhancement

#1001 Update Jest to v29 and user-event to v14
  jest.config.base.cjs
  jest.config.lint.cjs
  jest.setup.ts
  package-lock.json
  package.json
  packages/code-studio/src/main/AppMainContainer.test.tsx
  packages/code-studio/src/settings/FormattingSectionContent.test.tsx
  packages/components/src/BasicModal.test.tsx
  packages/components/src/DateTimeInput.test.tsx
  packages/components/src/EditableItemList.test.tsx
  packages/components/src/ItemList.test.tsx
  packages/components/src/TimeInput.test.tsx
  packages/components/src/UISwitch.test.tsx
  packages/components/src/context-actions/ContextActions.test.tsx
  packages/components/src/context-actions/ContextMenuItem.test.tsx
  packages/components/src/context-actions/__snapshots__/ContextActions.test.tsx.snap
  packages/components/src/modal/Modal.test.tsx
  packages/components/src/modal/ModalHeader.test.tsx
  packages/console/src/ConsoleStatusBar.test.tsx
  packages/console/src/command-history/CommandHistory.test.tsx
  packages/console/src/command-history/CommandHistoryActions.test.tsx
  packages/dashboard-core-plugins/src/controls/dropdown-filter/DropdownFilter.test.tsx
  packages/dashboard-core-plugins/src/panels/FileExplorerPanel.test.tsx
  packages/dashboard-core-plugins/src/panels/FilterSetManagerPanel.test.tsx
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.test.tsx
  packages/embed-grid/jest.config.cjs
  packages/eslint-config/index.js
  packages/file-explorer/src/FileListItemEditor.test.tsx
  packages/iris-grid/src/IrisGridCopyHandler.test.tsx
  packages/iris-grid/src/IrisGridModel.test.ts
  packages/iris-grid/src/IrisGridTestUtils.ts
  packages/iris-grid/src/PartitionSelectorSearch.test.tsx
  packages/iris-grid/src/TableViewportUpdater.test.jsx
  packages/iris-grid/src/sidebar/ChartBuilder.test.tsx
  packages/iris-grid/src/sidebar/TableCsvExporter.test.tsx
  packages/iris-grid/src/sidebar/aggregations/AggregationEdit.test.tsx
  packages/iris-grid/src/sidebar/aggregations/Aggregations.test.tsx
  packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.test.tsx
  packages/mocks/package.json
  packages/utils/src/Pending.test.ts
  packages/utils/src/Pending.ts
  packages/utils/src/TestUtils.ts
  packages/utils/src/index.ts
Labels: internal

#1007 Fix silent error when saving notebook with duplicate name
  packages/code-studio/src/storage/grpc/GrpcFileStorage.ts
Labels: bug

#1002 Move column specific formatting into a new dropdown section
  packages/code-studio/src/settings/ColumnSpecificSectionContent.test.tsx
  packages/code-studio/src/settings/ColumnSpecificSectionContent.tsx
  packages/code-studio/src/settings/ColumnTypeOptions.tsx
  packages/code-studio/src/settings/DateTimeOptions.tsx
  packages/code-studio/src/settings/FormattingSectionContent.tsx
  packages/code-studio/src/settings/SettingsMenu.tsx
  packages/code-studio/src/settings/SettingsUtils.tsx
  packages/code-studio/src/settings/TimeZoneOptions.tsx
Labels: enhancement

#1014 Adjust margin in column header grouping list
  packages/iris-grid/src/sidebar/visibility-ordering-builder/sortable-tree/TreeItem.scss
Labels: enhancement

#1012 [Fix] Toast Wrapping with Overridden Plotly Styles
  CONTRIBUTING.md
  packages/chart/src/Chart.scss
Labels: bug

#1016 Cancelled promises reject immediately
  packages/dashboard-core-plugins/src/panels/ChartPanel.test.tsx
  packages/utils/src/PromiseUtils.ts
Labels: bug

#1019 Fix up groupedColumns in TreeTables
  packages/iris-grid/src/IrisGridTreeTableModel.ts
  packages/jsapi-shim/src/dh.types.ts
Labels: bug

#1023 Version Bump v0.26.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/pouch-storage/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal

#1026 Deleting file deletes last selected entity
  packages/components/src/ItemListItem.tsx
Labels: bug

#1028 Clicking save on a new notebook automatically selects input field
  packages/golden-layout/src/controls/Tab.ts
Labels: enhancement

#1025 Fix vertical scrollbar appearing over column header group names
  packages/grid/src/GridMetricCalculator.ts
  packages/grid/src/GridRenderer.ts
  tests/table.spec.ts
  tests/table.spec.ts-snapshots/can-open-a-table-with-column-header-groups-1-chromium-linux.png
  tests/table.spec.ts-snapshots/can-open-a-table-with-column-header-groups-1-firefox-linux.png
  tests/table.spec.ts-snapshots/can-open-a-table-with-column-header-groups-1-webkit-linux.png
Labels: bug

#1031 Existing rows in append-only tables cannot be edited
  packages/iris-grid/src/IrisGridTableModelTemplate.ts
Labels: bug

#1037 Grid selection tick mark goes away after deselection
  packages/grid/src/Grid.test.tsx
  packages/grid/src/Grid.tsx
Labels: bug

#1029 Fix cell overflow viewer with browser zoom
  packages/iris-grid/src/IrisGridCellOverflowModal.tsx
Labels: bug

#1039 Version Bump v0.26.1
  lerna.json
  package-lock.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/file-explorer/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/pouch-storage/package.json
Labels: internal

#1043 Bump babel versions
  package-lock.json
  package.json
  packages/babel-preset/package.json
  packages/console/package.json
Labels: internal

#995 Update to Node v18
  .github/workflows/create-release.yml
  .github/workflows/e2e.yml
  .github/workflows/publish-alpha.yml
  .github/workflows/publish-nightly.yml
  .github/workflows/publish-packages.yml
  .github/workflows/unit.yml
  .nvmrc
Labels: internal

#1042 Update e2e tests to use the latest `edge` release
  .github/workflows/e2e.yml
Labels: internal

#982 Update plotly.js to v2.18.0
  package-lock.json
  package.json
  packages/chart/package.json
Labels: internal

#1047 Fix freeze column from context menu
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
Labels: bug

#1013 Validate custom column names
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/sidebar/CustomColumnBuilder.test.tsx
  packages/iris-grid/src/sidebar/CustomColumnBuilder.tsx
  packages/iris-grid/src/sidebar/CustomColumnInput.test.tsx
  packages/iris-grid/src/sidebar/CustomColumnInput.tsx
  packages/iris-grid/src/sidebar/InputEditor.tsx
Labels: bug

#1051 Add optional worker authentication
  packages/code-studio/src/main/AppInit.tsx
  packages/code-studio/src/main/SessionUtils.ts
  packages/jsapi-shim/src/dh.types.ts
Labels: enhancement

#1053 Change log levels in requestParentLoginOptions from info to debug
  packages/code-studio/src/main/SessionUtils.ts
Labels: internal

#1055 Version Bump v0.27.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/pouch-storage/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal

#1040 Overwriting file keeps old tab open with old contents
  packages/dashboard-core-plugins/src/ConsolePlugin.tsx
  packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx
  packages/dashboard/src/layout/LayoutUtils.ts
  packages/file-explorer/src/NewItemModal.tsx
  packages/golden-layout/src/container/ItemContainer.ts
  packages/golden-layout/src/container/index.ts
Labels: bug

#1036 Don't allow starting or ending links from non-filterable columns
  packages/dashboard-core-plugins/src/linker/Linker.tsx
  packages/dashboard-core-plugins/src/linker/LinkerUtils.tsx
Labels: enhancement

#974 Added goto value feature
  packages/code-studio/src/styleguide/MockIrisGridTreeModel.ts
  packages/grid/src/Grid.tsx
  packages/iris-grid/src/GotoRow.scss
  packages/iris-grid/src/GotoRow.tsx
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/IrisGridModel.ts
  packages/iris-grid/src/IrisGridProxyModel.ts
  packages/iris-grid/src/IrisGridTableModel.ts
  packages/iris-grid/src/IrisGridTableModelTemplate.ts
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
  packages/jsapi-shim/src/dh.types.ts
  packages/jsapi-utils/src/TableUtils.ts
  tests/table.spec.ts
  tests/table.spec.ts-snapshots/tests-table-operations-go-to-1-chromium-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-go-to-1-firefox-linux.png
  tests/table.spec.ts-snapshots/tests-table-operations-go-to-1-webkit-linux.png
Labels: enhancement

#1059 fix: Pasting with smart quotes causes double paste in monaco
  packages/code-studio/src/main/AppMainContainer.tsx
Labels: bug

#1063 fix: corrected "Filter By Value" to be title cased "by"
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
Labels: bug

#1052 Fix resizing/hiding layout hint hidden columns. Fix resetting layout hints
  packages/grid/src/GridMetricCalculator.ts
  packages/grid/src/mouse-handlers/GridColumnSeparatorMouseHandler.ts
  packages/grid/src/mouse-handlers/GridRowSeparatorMouseHandler.ts
  packages/grid/src/mouse-handlers/GridSeparatorMouseHandler.ts
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/IrisGridMetricCalculator.ts
  packages/iris-grid/src/IrisGridTableModelTemplate.ts
  packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.test.tsx
  packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.tsx
  packages/iris-grid/src/sidebar/visibility-ordering-builder/sortable-tree/utilities.ts
Labels: bug

#981 Add support for plotting series point shapes and point size
  packages/chart/src/ChartUtils.test.ts
  packages/chart/src/ChartUtils.ts
  packages/jsapi-shim/src/dh.types.ts
  tests/console.spec.ts
  tests/figure.spec.ts
  tests/figure.spec.ts-snapshots/can-set-point-shape-and-size-1-chromium-linux.png
  tests/figure.spec.ts-snapshots/can-set-point-shape-and-size-1-firefox-linux.png
  tests/figure.spec.ts-snapshots/can-set-point-shape-and-size-1-webkit-linux.png
  tests/notebook.spec.ts
  tests/table.spec.ts
  tests/utils.ts
Labels: enhancement
