Repository deephaven/web-client-ui, pull requests merged in 2023-02, with the labels that each got.

#1048 feat: Expand all UI support for hierarchical tables
  packages/code-studio/src/styleguide/MockIrisGridTreeModel.ts
  packages/grid/src/ExpandableGridModel.ts
  packages/grid/src/Grid.tsx
  packages/grid/src/MockTreeGridModel.ts
  packages/grid/src/mouse-handlers/GridRowTreeMouseHandler.ts
  packages/iris-grid/src/IrisGridProxyModel.ts
  packages/iris-grid/src/IrisGridTreeTableModel.ts
  packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
  packages/jsapi-shim/src/dh.types.ts
Labels: enhancement

#1066 Version Bump v0.28.0
  lerna.json
  package-lock.json
  packages/babel-preset/package.json
  packages/chart/package.json
  packages/code-studio/package.json
  packages/components/package.json
  packages/console/package.json
  packages/dashboard-core-plugins/package.json
  packages/dashboard/package.json
  packages/embed-chart/package.json
  packages/embed-grid/package.json
  packages/eslint-config/package.json
  packages/file-explorer/package.json
  packages/filters/package.json
  packages/golden-layout/package.json
  packages/grid/package.json
  packages/icons/package.json
  packages/iris-grid/package.json
  packages/jsapi-components/package.json
  packages/jsapi-shim/package.json
  packages/jsapi-utils/package.json
  packages/log/package.json
  packages/mocks/package.json
  packages/pouch-storage/package.json
  packages/prettier-config/package.json
  packages/react-hooks/package.json
  packages/redux/package.json
  packages/storage/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
  packages/utils/package.json
Labels: internal

#1057 feat: Use Conventional Commits for release management/PRs
  .github/scripts/label-check-one-of.sh
  .github/workflows/cla.yml
  .github/workflows/conventional-pr-check.yml
  .github/workflows/create-release.yml
  .github/workflows/label-check-ci.yml
  .github/workflows/publish-alpha.yml
  .github/workflows/publish-nightly.yml
  .github/workflows/publish-packages.yml
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
Labels: internal, breaking

#986 refactor: Mark immutable arrays as readonly
  packages/components/src/DraggableItemList.tsx
  packages/components/src/ItemList.tsx
  packages/components/src/navigation/Menu.tsx
  packages/dashboard-core-plugins/src/panels/ChartPanel.tsx
  packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
  packages/grid/src/ColumnHeaderGroup.ts
  packages/grid/src/EditableGridModel.ts
  packages/grid/src/Grid.tsx
  packages/grid/src/GridMetricCalculator.ts
  packages/grid/src/GridMetrics.ts
  packages/grid/src/GridRange.ts
  packages/grid/src/GridRenderer.ts
  packages/grid/src/GridUtils.ts
  packages/grid/src/mouse-handlers/GridColumnMoveMouseHandler.ts
  packages/iris-grid/src/ColumnHeaderGroup.ts
  packages/iris-grid/src/CommonTypes.tsx
  packages/iris-grid/src/CrossColumnSearch.tsx
  packages/iris-grid/src/IrisGrid.tsx
  packages/iris-grid/src/IrisGridCopyHandler.tsx
  packages/iris-grid/src/IrisGridModel.ts
  packages/iris-grid/src/IrisGridModelUpdater.tsx
  packages/iris-grid/src/IrisGridProxyModel.ts
  packages/iris-grid/src/IrisGridRenderer.ts
  packages/iris-grid/src/IrisGridTableModelTemplate.ts
  packages/iris-grid/src/IrisGridUtils.ts
  packages/iris-grid/src/PendingDataBottomBar.tsx
  packages/iris-grid/src/sidebar/ChartBuilder.tsx
  packages/iris-grid/src/sidebar/CustomColumnBuilder.tsx
  packages/iris-grid/src/sidebar/RollupRows.tsx
  packages/iris-grid/src/sidebar/SelectDistinctBuilder.tsx
  packages/iris-grid/src/sidebar/TableCsvExporter.tsx
  packages/iris-grid/src/sidebar/TableSaver.tsx
  packages/iris-grid/src/sidebar/aggregations/AggregationEdit.tsx
  packages/iris-grid/src/sidebar/aggregations/AggregationUtils.ts
  packages/iris-grid/src/sidebar/aggregations/Aggregations.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormatEditor.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingMenu.tsx
  packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.ts
  packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.tsx
  packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilderUtils.ts
  packages/iris-grid/src/sidebar/visibility-ordering-builder/sortable-tree/types.ts
  packages/iris-grid/src/sidebar/visibility-ordering-builder/sortable-tree/utilities.ts
  packages/jsapi-shim/src/dh.types.ts
  packages/jsapi-utils/src/TableUtils.ts
  packages/utils/src/DataUtils.ts
  packages/utils/src/RangeUtils.ts
  packages/utils/src/index.ts
Labels: internal

#1082 fix: DH-14237: down arrow in console not returning to blank field
  packages/console/src/Console.test.tsx
  packages/console/src/ConsoleInput.tsx
Labels: bug

#1092 fix: Remove default export in jsapi-types
  packages/jsapi-bootstrap/src/ApiBootstrap.tsx
  packages/jsapi-shim/src/dh.ts
  packages/jsapi-shim/src/dh.types.ts
  packages/jsapi-shim/src/index.ts
  packages/jsapi-types/src/index.ts
Labels: bug
